"""Opt-in roots for tests that consume external capture artifacts.

Private capture corpora are integration evidence, not release-test fixtures.
No legacy host path is consulted unless the corresponding environment variable
is set explicitly for the test process.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Optional


_CAPTURE_ROOT_ENV = "BD_TEST_CAPTURE_ROOT"
_STRICT_CAPTURE_ROOT_ENV = "BD_TEST_STRICT_CAPTURE_ROOT"


@dataclass(frozen=True)
class CaptureFixtureLane:
    """A disabled-by-default view of one external capture fixture root."""

    env_name: str
    root: Optional[Path]

    @property
    def enabled(self) -> bool:
        return self.root is not None

    @staticmethod
    def _validate_name(name: str) -> str:
        candidate = Path(name)
        if not name or candidate.name != name or name in (".", ".."):
            raise ValueError("capture artifact name must be a single file name")
        return name

    def path(self, name: str) -> Path:
        name = self._validate_name(name)
        if self.root is None:
            raise RuntimeError(
                f"external capture lane disabled; set {self.env_name} explicitly"
            )
        return self.root / name

    def has(self, *names: str) -> bool:
        if self.root is None:
            return False
        return all(self.path(name).is_file() for name in names)


#: In-repo, committed, SYNTHETIC corpus. Not a private capture root: every
#: artifact is generated by ``tools/make_synthetic_capture_corpus.py`` and
#: carries only zero-entropy secret-shaped values.
_SYNTHETIC_ROOT = Path(__file__).resolve().parent / "tests" / "capture_corpus_synthetic"


def capture_fixture_lane(
    *, strict: bool = False, allow_synthetic: bool = False
) -> CaptureFixtureLane:
    """Resolve an explicitly configured external capture-fixture lane.

    The regular lane uses ``BD_TEST_CAPTURE_ROOT``.  The separately installed
    strict corpus uses ``BD_TEST_STRICT_CAPTURE_ROOT`` so enabling one private
    corpus cannot accidentally discover the other.

    ``allow_synthetic`` falls back to the committed synthetic corpus when no
    private root is configured, so the 65 tests that consume capture artifacts
    RUN everywhere -- previously they skipped in every environment including CI,
    because a private corpus is never committed.

    IT IS OPT-IN PER CALL SITE, AND DELIBERATELY SO. Flipping the default would
    break ``test_default_lane_is_disabled_without_explicit_root``, and that guard
    is worth keeping: its neighbour
    ``test_capture_modules_do_not_embed_legacy_private_roots`` shows what the
    pair exists to prevent -- a module silently reading somebody's private
    corpus off a hardcoded host path. A committed in-repo synthetic corpus is
    not that, but the distinction should be visible at the call site rather than
    buried in a default.

    A configured private root still WINS when present, so a real corpus is used
    for higher fidelity wherever one is installed.
    """

    env_name = _STRICT_CAPTURE_ROOT_ENV if strict else _CAPTURE_ROOT_ENV
    raw = os.environ.get(env_name, "").strip()
    if not raw:
        if allow_synthetic and _SYNTHETIC_ROOT.is_dir():
            return CaptureFixtureLane(env_name=env_name, root=_SYNTHETIC_ROOT)
        return CaptureFixtureLane(env_name=env_name, root=None)
    root = Path(raw).expanduser()
    if not root.is_absolute():
        raise ValueError(f"{env_name} must be an absolute path")
    return CaptureFixtureLane(env_name=env_name, root=root.resolve(strict=False))


def validate_capture_fixture_roots() -> None:
    """Fail early when an explicitly configured fixture root is unusable."""

    for strict in (False, True):
        lane = capture_fixture_lane(strict=strict)
        if lane.enabled and not lane.root.is_dir():
            raise ValueError(f"{lane.env_name} directory not found: {lane.root}")
