"""bulk_downloader.capture_workbench -- thin re-export shim over capture_workbench_impl/.

Decomposed @v3.66.451 (DECOMP-LEAF cut 4). ADD-only (R1 shim-over-rm); the posture
guard that inspects this module now iterates the package submodules. Re-exports the
COMPLETE surface explicitly (no `import *`)."""

from .capture_workbench_impl import (  # noqa: F401
    CLIENT_COMPUTED,
    CP_ADDITIONAL_CAPTURE,
    CP_CLASSIFIER_SUFFICIENT,
    CP_DETECTOR_CONFIG,
    CP_NO_ACTION,
    CP_SELECTOR_WORKFLOW,
    CP_UNRECOVERABLE,
    DetectorDraft,
    DraftPattern,
    IDENTITY,
    INVARIANT,
    PROVENANCE,
    RENDITION,
    ROTATING_OPAQUE,
    SIGNING,
    STABLE_ID,
    Slot,
    WORKBENCH_VERSION,
    _AFFECTS,
    _BAND_ORDER,
    _CANDIDATE_FLOOR,
    _CONF_BY_VERDICT,
    _FRAGILITY,
    _GENERALIZES_KIND,
    _GENERIC_BUCKETS,
    _HEXISH,
    _ID_SHAPES,
    _LOCAL_KIND,
    _METHOD_ONLY_KIND,
    _NODE_WEIGHT,
    _OBSERVED_BASES,
    _PATH_SIGN_TYPE,
    _RATIONALE_BY_VERDICT,
    _RENDITION_SIGNAL,
    _REUSABLE_CLASS_KIND,
    _SIGNING_SHAPES,
    _SIGN_MARKER,
    _STAB,
    _STORAGE_HINT,
    _STRUCTURAL_WORD,
    _UNC_W_EDGE,
    _UNC_W_FLOOR,
    _UNC_W_SKELETON,
    _UNC_W_SRC_UNKNOWN,
    _UNC_W_STRUCTURE,
    _admit_candidate,
    _assumption_kind,
    _assumption_stability,
    _assumptions_for_recommendation,
    _blast_radius,
    _bodies_retained,
    _candidate_signals,
    _change_plan,
    _contradictions,
    _decision_confidence,
    _derive_pattern,
    _downstream_sets,
    _generalization,
    _impact,
    _kv_pairs,
    _mask_path_signing,
    _node_weight_regimes,
    _rank_by,
    _request_key_of,
    _segment_is_addressable,
    _segment_regex,
    _segment_role,
    _sensitivity,
    _sharded_run_map,
    _slot_evidence,
    _slot_strengthen,
    _uncertainty_flow,
    _uncertainty_plan,
    _upstream_assumptions,
    _value_for_pattern,
    _verdict_for_param,
    build_workbench,
    classify_value,
    goal_skeleton,
)

__all__ = [
    "goal_skeleton",
    "build_workbench",
]
