"""bulk_downloader.provider_resolve -- thin re-export shim over provider_resolve_impl/.

Decomposed @v3.66.454 (DECOMP-LEAF cut 6, final). ADD-only (R1 shim-over-rm). Re-exports
the COMPLETE surface explicitly (no `import *`). _default_http_get is re-exported here and
resolve_provider_embed reads it back off THIS module at call time, so the documented
test monkeypatch `provider_resolve._default_http_get = ...` stays effective."""

from .provider_resolve_impl import (  # noqa: F401
    CacheWrite,
    DEFAULT_CACHE_TTL_SECONDS,
    HttpGet,
    SSRFBlocked,
    _BRIGHTCOVE_PLAYBACK_URL_TMPL,
    _JWPLAYER_ALLOWED_SCHEMES,
    _JWPLAYER_DRM_MARKER_KEYS,
    _JWPLAYER_FEED_URL_TMPL,
    _JWPLAYER_MEDIA_URL_TMPL,
    _JWPLAYER_SIGNED_URL_MARKER_KEYS,
    _JWP_DASH_MIMES,
    _JWP_HLS_MIMES,
    _JWP_MP4_MIMES,
    _RESOLVERS,
    _SSRFGuardedTransport_factory,
    _SSRF_GUARDED_TRANSPORT_CLS,
    _VIMEO_CONFIG_URL_TMPL,
    _WISTIA_MEDIA_URL_TMPL,
    _YOUTUBE_WATCH_URL_TMPL,
    _YT_CIPHER_SUBPROC_TIMEOUT_SECONDS,
    _YT_CIPHER_YTDLP_PATH_CACHE,
    _YT_DECIPHER_FN_RE,
    _YT_DECIPHER_STMT_RE,
    _YT_JS_URL_RE,
    _YT_PLAYER_JS_HOST_SUFFIXES,
    _YT_PLAYER_RESPONSE_RE,
    _YT_TRANSFORM_METHOD_RE,
    _YT_VIDEO_ID_RE,
    _apply_honeypot_filter,
    _apply_yt_decipher_ops,
    _build_yt_decipher_ops,
    _cache_lookup,
    _classify_ip,
    _classify_yt_transform,
    _coerce_int,
    _decipher_signed_formats,
    _decipher_signed_formats_playerjs,
    _decipher_signed_formats_ytdlp,
    _default_http_get,
    _honeypot_drop_threshold,
    _honeypot_score_threshold,
    _honeypot_score_threshold_raw,
    _is_safe_public_host,
    _jwplayer_check_drm_markers,
    _jwplayer_emit_sources,
    _make_default_http_get,
    _now,
    _primary_id,
    _resolve_jwplayer_feed,
    _resolve_jwplayer_media,
    _resolve_jwplayer_selfhosted,
    _slice_balanced_json,
    _yt_cipher_backend,
    _yt_cipher_ytdlp_path,
    build_signing_callback,
    resolve_brightcove,
    resolve_jwplayer,
    resolve_provider_embed,
    resolve_vimeo,
    resolve_wistia,
    resolve_youtube,
)

__all__ = [
    "HttpGet",
    "CacheWrite",
    "DEFAULT_CACHE_TTL_SECONDS",
    "SSRFBlocked",
    "resolve_provider_embed",
    "resolve_vimeo",
    "resolve_youtube",
    "resolve_brightcove",
    "resolve_wistia",
    "resolve_jwplayer",
    "build_signing_callback",
]
