"""Whether a container restart fires SessionStart was assumed, never measured.

@882. `.claude/hooks/session-start.sh` repairs a rolled-back checkout and
reconverges the environment, but it only runs on a SessionStart event
(startup|resume|clear|compact). Whether a mid-session CONTAINER RESTART produces
one is UNKNOWN: the hook's own comments and the @873/@879/@881 suites all assume
it does, and not one of them establishes it. If it does not, a rollback sits
unrepaired for the rest of the session and every source read after it is against
a stale tree -- the failure that started this whole line of work.

A hook cannot log the runs it did not make. Self-logging is therefore the wrong
instrument: with no SessionStart, nothing writes anything, and the absent entry
is indistinguishable from a hook that was never installed. CLAUDE.md section 0,
exactly -- a denominator that structurally excludes its subject.

/proc/sys/kernel/random/boot_id is regenerated by the kernel on every boot, so
recording it makes "the machine changed under you" a positive fact rather than
an absent one. The hook writes it; `bd-restart-check` reads it back.

AND THE READING ONLY WORKS MID-SESSION. A mismatch measured at hook time is
ambiguous -- "the restart fired SessionStart" and "the restart fired nothing,
then a new session started later" give the identical result, because the hook is
running now and the record predates the restart either way. Checked from inside
a running session, with no new session begun, a mismatch can only mean the hook
did not run. That is why this is a tool and not another branch in the hook.
"""
from __future__ import annotations

import json
import os
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
TOOL = REPO / "toolchain" / "bin" / "bd-restart-check"
HOOK = REPO / ".claude" / "hooks" / "session-start.sh"

sys.path.insert(0, str(REPO / "toolchain" / "bin"))


def _load():
    """Import an EXTENSIONLESS bd-* tool.

    `spec_from_file_location` alone returns None here, because it infers the
    loader from the suffix and there is no suffix -- the 460-odd tracked
    executable python-shebang `bd-*` scripts CLAUDE.md section 1 warns a `*.py`
    glob cannot see. The loader has to be named explicitly.
    """
    import importlib.util
    from importlib.machinery import SourceFileLoader
    loader = SourceFileLoader("bd_restart_check", str(TOOL))
    spec = importlib.util.spec_from_loader(loader.name, loader)
    m = importlib.util.module_from_spec(spec)
    loader.exec_module(m)
    return m


def _run(state: Path, extra=()):
    return subprocess.run([sys.executable, str(TOOL), "--state", str(state),
                           "--json", *extra],
                          capture_output=True, text=True, timeout=60)


# --------------------------------------------------------------------------- #
# the three states, driven through the pure classifier                         #
# --------------------------------------------------------------------------- #

def test_a_changed_boot_id_is_reported_as_restarted():
    """THE POINT. Different boot, and the hook has not run since -- so if no new
    session was started, SessionStart does not fire on a container restart."""
    m = _load()
    v = m.classify("boot-AAA", {"boot_id": "boot-BBB", "when": "w", "source": "startup"})
    assert v["exit"] == 1, v
    assert v["status"] == "restarted"
    assert "UNREPAIRED" in v["detail"] or "unrepaired" in v["detail"].lower(), (
        "the verdict does not name the consequence -- a reader who sees "
        "'restarted' still does not know their source reads are suspect: %r"
        % v["detail"])


def test_an_unchanged_boot_id_is_ok():
    m = _load()
    v = m.classify("boot-AAA", {"boot_id": "boot-AAA", "when": "w", "source": "startup"})
    assert v["exit"] == 0 and v["status"] == "ok", v


def test_a_missing_record_is_unevaluable_not_ok():
    """Unknown is a third state. 'The hook never wrote anything' is not
    evidence that nothing happened -- it is the absence of evidence, and
    rendering it as exit 0 is the failure this whole tool exists to avoid."""
    m = _load()
    v = m.classify("boot-AAA", None)
    assert v["exit"] == 2, v
    assert v["status"] == "unevaluable"


def test_a_kernel_without_boot_id_is_unevaluable_not_ok():
    m = _load()
    v = m.classify(None, {"boot_id": "boot-AAA", "when": "w", "source": "s"})
    assert v["exit"] == 2 and v["status"] == "unevaluable", v


# --------------------------------------------------------------------------- #
# end to end, against real files                                               #
# --------------------------------------------------------------------------- #

def test_the_tool_reads_a_real_state_file(tmp_path):
    state = tmp_path / "boot_state"
    state.write_text("definitely-not-this-machines-boot-id\n2026-01-01T00:00:00Z\nstartup\n")
    r = _run(state)
    assert r.returncode == 1, (r.returncode, r.stdout, r.stderr)
    assert json.loads(r.stdout)["status"] == "restarted"


def test_an_absent_state_file_exits_two(tmp_path):
    r = _run(tmp_path / "nope")
    assert r.returncode == 2, (r.returncode, r.stdout)
    assert json.loads(r.stdout)["status"] == "unevaluable"


def test_an_empty_state_file_is_unevaluable_not_ok(tmp_path):
    """A truncated write must not read as agreement. The hook writes this file
    with a plain redirect, so a killed process can leave it empty."""
    state = tmp_path / "boot_state"
    state.write_text("")
    r = _run(state)
    assert r.returncode == 2, (r.returncode, r.stdout)


def test_the_selftest_passes():
    r = subprocess.run([sys.executable, str(TOOL), "--selftest"],
                       capture_output=True, text=True, timeout=60)
    assert r.returncode == 0, r.stdout + r.stderr
    assert "SELFTEST PASS" in r.stdout


# --------------------------------------------------------------------------- #
# the hook must actually write the record the tool reads                       #
# --------------------------------------------------------------------------- #

def test_the_hook_records_the_boot_id(tmp_path):
    """Otherwise the tool grades a file nobody writes and always says UNKNOWN --
    a gate that cannot see its subject, in the pair built to avoid one."""
    from test_v3_66_879_provision_trigger_sees_its_subject import (
        _origin_and_clone,
    )
    _origin, clone = _origin_and_clone(tmp_path)
    fake_home = tmp_path / "home"
    fake_home.mkdir()
    env = dict(os.environ)
    env["CLAUDE_CODE_REMOTE"] = "true"
    env["CLAUDE_PROJECT_DIR"] = str(clone)
    env["HOME"] = str(fake_home)
    env.pop("CLAUDE_ENV_FILE", None)
    subprocess.run(["bash", str(HOOK)], cwd=str(clone),
                   input='{"source":"startup"}', capture_output=True,
                   text=True, timeout=300, env=env)
    state = fake_home / ".bd_boot_state"
    assert state.exists(), (
        "the hook did not write the boot record, so bd-restart-check can only "
        "ever return UNEVALUABLE")
    lines = state.read_text().splitlines()
    assert len(lines) >= 3, "the record is missing fields: %r" % lines
    assert lines[2] == "startup", (
        "the record does not carry the hook source, so a reader cannot tell "
        "which event last ran it: %r" % lines)


def test_the_hook_writing_the_record_cannot_break_the_repair(tmp_path):
    """The record is written last and never gated on. A failure there must not
    cost the repair, which is the part that matters."""
    from test_v3_66_879_provision_trigger_sees_its_subject import (
        _head, _origin_and_clone, _tip,
    )
    _origin, clone = _origin_and_clone(tmp_path)
    env = dict(os.environ)
    env["CLAUDE_CODE_REMOTE"] = "true"
    env["CLAUDE_PROJECT_DIR"] = str(clone)
    env["HOME"] = "/nonexistent-home-that-cannot-be-written"
    env.pop("CLAUDE_ENV_FILE", None)
    r = subprocess.run(["bash", str(HOOK)], cwd=str(clone),
                       input='{"source":"startup"}', capture_output=True,
                       text=True, timeout=300, env=env)
    assert _head(clone) == _tip(clone), (
        "an unwritable boot-state path prevented the rollback repair. "
        "stderr=%r" % r.stderr)
    assert r.returncode == 0, r.stderr
