"""Route-map invariant for the app.py / F5.1 decomposition (characterization).

The F5.1 contract: moving a view into a blueprint changes its endpoint *label*
(Flask prefixes it `domain.func`) but must NOT change the externally observable
routing surface -- the (rule, methods) of every route -- and must not lose or rename
a view. This test freezes that surface from the F5.1-OPEN tree (v3.66.392, 944 rules); re-frozen at v3.66.467 to 945 (the /api/plugins/config feature route); re-frozen at v3.66.505 to 947 (the Bucket 2 .env editor GET+POST /api/settings/envfile)
and asserts it byte-for-byte after every cut.

Keyed on (rule, sorted-methods, BARE function name) -- the endpoint's blueprint
prefix is stripped, so a clean move into a blueprint diffs EMPTY, while a
rename / added / removed route or a changed method set fails loudly. Because the
registration block is fail-open, a silently-failed register_routes() drops routes
from the url_map -> this test catches it.

Baseline: `tests/route_map_baseline.txt` (950 lines),
generated by `tools/route_map_snapshot.py` from the pre-F5.1 tree. Re-freeze ONLY at
F5.1-open and at F5.1-close (the intentionally-final surface) -- never mid-arc, or
the gate is defeated. Runner-safe: zero-arg fns, paths derived from __file__.
"""
import os
import hashlib
from pathlib import Path

os.environ.setdefault("BD_HOME", os.environ.get("BD_HOME", "/tmp/bd_route_inv_home"))
os.environ.setdefault("BD_DISABLE_KEEPALIVE", "1")

_BASELINE = Path(__file__).resolve().parent / "route_map_baseline.txt"
# sha256 of the F5.1-OPEN baseline (v3.66.392). If you intentionally re-freeze the
# baseline at F5.1-open/close, update this too -- it guards against an accidental
# baseline edit.
# v3.66.716: re-frozen. The /api/sched_exports family (4 routes) was REMOVED by operator
# decision -- a shadow blueprint nothing called, superseded by /api/scheduled_exports. This
# is an INTENTIONAL surface change, so the contract is re-cut; the SHA pin exists to make an
# ACCIDENTAL baseline edit impossible, and it did its job (it blocked until stated).
_BASELINE_SHA = "24221c4dc4a7e32f10bda615cd5a86543c4d064ebc366e14070fa575711655c5"


def _live_snapshot() -> str:
    """Canonical (rule, methods, bare-endpoint) snapshot of the live url_map."""
    import importlib
    app = importlib.import_module("bulk_downloader.app").app
    lines = []
    for r in app.url_map.iter_rules():
        methods = ",".join(sorted(m for m in r.methods if m not in ("HEAD", "OPTIONS")))
        bare = r.endpoint.rsplit(".", 1)[-1]   # strip blueprint prefix
        lines.append(f"{r.rule}\t{methods}\t{bare}")
    lines.sort()
    return "\n".join(lines) + "\n"


def test_route_map_baseline_file_present_and_unmodified():
    """The frozen baseline exists and matches its recorded sha (no accidental edit)."""
    assert _BASELINE.exists(), (
        f"missing {_BASELINE.name}; generate with "
        f"`python3 tools/route_map_snapshot.py > tests/route_map_baseline.txt` at F5.1-open")
    got = hashlib.sha256(_BASELINE.read_bytes()).hexdigest()
    assert got == _BASELINE_SHA, (
        f"route_map_baseline.txt sha changed ({got[:12]} != {_BASELINE_SHA[:12]}). "
        f"If you intentionally re-froze the baseline at F5.1 open/close, update "
        f"_BASELINE_SHA; otherwise the baseline was edited by mistake.")


def test_route_surface_unchanged_since_f51_open():
    """The live (rule, methods, bare-name) surface equals the frozen F5.1-OPEN baseline.

    A clean blueprint extraction diffs EMPTY (only the endpoint *prefix* changes,
    which is stripped). Any added/removed/re-pathed route, changed method set, or
    renamed view function fails here -- including a silently-dropped fail-open
    registration."""
    baseline = _BASELINE.read_text(encoding="utf-8")
    live = _live_snapshot()
    if live == baseline:
        return
    b = set(baseline.splitlines())
    l = set(live.splitlines())
    removed = sorted(b - l)
    added = sorted(l - b)
    msg = ["route surface changed vs the F5.1-OPEN baseline (decomposition must be pure motion):"]
    if removed:
        msg.append(f"  REMOVED ({len(removed)}): " + "; ".join(removed[:8]) + (" ..." if len(removed) > 8 else ""))
    if added:
        msg.append(f"  ADDED ({len(added)}): " + "; ".join(added[:8]) + (" ..." if len(added) > 8 else ""))
    raise AssertionError("\n".join(msg))


def test_route_count_matches_baseline():
    """Fast canary: rule count equals the baseline's (986: prior 982 + the
    v3.66.639 /api/interop/{registry,register,acknowledge,enable} GOV-1b surface)."""
    n_base = sum(1 for _ in _BASELINE.read_text(encoding="utf-8").splitlines())
    n_live = sum(1 for _ in _live_snapshot().splitlines())
    assert n_live == n_base, (
        f"url_map rule count {n_live} != baseline {n_base} -- a route was added or dropped "
        f"(see test_route_surface_unchanged_since_f51_open for which)")
