"""The size-drift census must read the shape the app actually writes.

THE DEFECT THIS PINS. A hand-written version of this census (recorded in
project-knowledge/SESSION_CARRY.md) parsed sites_config.json as
``json.load(...).get("sites", {})``. The file is a FLAT {site_id: cfg}
mapping -- app.py:1276 writes ``{sid: dict(cfg)}`` and app.py:1334 iterates
``data.items()`` -- so that lookup could only ever return empty, and the
census reported a library it had never opened.

WHY THE ORIGINAL'S TEST DID NOT CATCH IT. It was tested against a synthetic
fixture built by hand in the same wrong shape, so the fixture encoded the
author's assumption rather than the app's behaviour. Section 0, one level up:
the denominator excluded the subject and the check reported clean.

SO THE FIXTURE HERE IS WRITTEN BY app.py ITSELF. `_save_sites_config` is the
one function that produces this file in production; driving it makes the app
the oracle, which is the only version of this test that cannot drift back.
A test that hand-builds the JSON would be re-asserting the belief under test.

The remaining tests cover the reason the census exists at all: the SPLIT by
sign, and the coverage accounting that stops a 0/0 result from reading as a
clean library when nothing was examined.
"""
from __future__ import annotations

import json
import os
import sys
import tempfile
from pathlib import Path

import pytest

_REPO = Path(__file__).resolve().parents[1]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from tools import census_file_size_drift as cen  # noqa: E402


@pytest.fixture
def lib(clean_workdir):
    """A download dir with an intact file, a truncated one, and a residue one,
    plus history rows for two sites sharing that directory and one orphan row
    whose site is not in any config."""
    import bulk_downloader.db as db
    from bulk_downloader import library_final as lf

    saved = db.DB_PATH
    db.DB_PATH = os.path.join(tempfile.mkdtemp(prefix="cen_db_"), "q.db")
    db.db_init()

    dl = Path(tempfile.mkdtemp(prefix="cen_dl_"))
    (dl / "sub").mkdir()
    (dl / "intact.mp4").write_bytes(b"\0" * 5000)
    (dl / "short.mp4").write_bytes(b"\0" * 100)       # recorded 9999 -> -9899
    (dl / "sub" / "residue.mp4").write_bytes(b"\0" * 8233)  # recorded 7000 -> +1233
    (dl / "b.mp4").write_bytes(b"\0" * 200)           # recorded 100   -> +100

    rows = [("A", "u1", "intact.mp4", 5000), ("A", "u2", "short.mp4", 9999),
            ("A", "u3", "residue.mp4", 7000), ("B", "u4", "b.mp4", 100),
            ("ghost", "u5", "g.mp4", 333)]
    for sid, url, fn, sz in rows:
        db.db_log(site_id=sid, site_name=sid, url=url, status="done",
                  filename=fn, file_size=sz)
    try:
        yield db, lf, dl
    finally:
        db.DB_PATH = saved


def _write_config_via_the_app(tmp_path, sites):
    """Produce sites_config.json using app.py's OWN writer.

    This is the point of the test: the fixture must be generated by the code
    that generates it in production, not hand-rolled to match a belief.
    """
    from bulk_downloader import app as bd_app

    target = Path(tmp_path) / "sites_config.json"
    saved_file, saved_cfg = bd_app.SITES_FILE, dict(bd_app.s_cfg)
    try:
        bd_app.SITES_FILE = target
        bd_app.s_cfg.clear()
        bd_app.s_cfg.update(sites)
        bd_app._save_sites_config()
    finally:
        bd_app.SITES_FILE = saved_file
        bd_app.s_cfg.clear()
        bd_app.s_cfg.update(saved_cfg)
    assert target.is_file(), "app._save_sites_config wrote no file"
    return target


def test_census_reads_the_shape_the_app_actually_writes(tmp_path):
    """RED against a ``.get("sites", {})`` reader: it returns {} here."""
    target = _write_config_via_the_app(
        tmp_path, {"s1": {"name": "wow", "download_dir": "/some/where"}})

    sites, ignored = cen.load_sites(str(target))

    assert set(sites) == {"s1"}, (
        f"the census did not find the site the app wrote: {sites!r}. The file "
        f"is a flat {{site_id: cfg}} mapping, not {{'sites': ...}}")
    assert sites["s1"].get("download_dir") == "/some/where"
    assert ignored == []


def test_the_written_file_has_no_sites_wrapper(tmp_path):
    """State the trap directly, so the failure names the cause.

    Without this, the test above still passes if someone 'helpfully' makes
    load_sites accept BOTH shapes -- and the register's wrong command would
    then look correct again.
    """
    target = _write_config_via_the_app(tmp_path, {"s1": {"name": "wow"}})
    raw = json.loads(target.read_text(encoding="utf-8"))

    assert "sites" not in raw or isinstance(raw.get("sites"), dict) and "s1" in raw, (
        "app.py wrote a 'sites' wrapper; the census's flat reader is now wrong")
    assert "s1" in raw, f"top-level keys are site ids; got {sorted(raw)}"


def test_a_non_mapping_config_is_refused_not_treated_as_empty():
    """UNKNOWN is a third state. An unusable config must raise, because the
    alternative -- an empty site set -- reports a spotless library."""
    p = Path(tempfile.mkdtemp(prefix="cen_bad_")) / "sites_config.json"
    p.write_text('["not", "a", "mapping"]', encoding="utf-8")
    with pytest.raises(cen.CensusError):
        cen.load_sites(str(p))

    p.write_text("{not json", encoding="utf-8")
    with pytest.raises(cen.CensusError):
        cen.load_sites(str(p))


def test_drift_is_split_by_sign_not_totalled(lib):
    """The split IS the decision: a truncation and residue must not merge."""
    db, lf, dl = lib
    rep = cen.census({"A": {"download_dir": str(dl)}}, db, lf)

    trunc = {r["filename"]: r for r in rep["truncations"]}
    res = {r["filename"]: r for r in rep["residue"]}
    assert "short.mp4" in trunc, f"truncation not reported: {rep['truncations']}"
    assert trunc["short.mp4"]["delta_bytes"] == -9899
    assert "residue.mp4" in res, f"residue not reported: {rep['residue']}"
    assert res["residue.mp4"]["delta_bytes"] == 1233
    assert "intact.mp4" not in trunc and "intact.mp4" not in res, (
        "an intact file was reported as drifted")


def test_two_sites_sharing_a_download_dir_are_both_examined(lib):
    """The dedupe bug the register's version shipped.

    list_size_drift filters by site_id, so skipping an already-seen
    download_dir drops that site's rows entirely instead of avoiding work.
    """
    db, lf, dl = lib
    rep = cen.census({"A": {"download_dir": str(dl)},
                      "B": {"download_dir": str(dl)}}, db, lf)

    assert {r["filename"] for r in rep["residue"]} >= {"b.mp4"}, (
        "site B shares A's download_dir and was skipped; its rows were never "
        f"examined: {rep['residue']}")
    assert rep["covered_rows"] == 4, rep


def test_rows_whose_site_is_gone_are_reported_not_silently_dropped(lib):
    """The deploy box's actual state: every done row belonged to a site that
    no longer exists, so a 0/0 result meant 'examined nothing'."""
    db, lf, dl = lib
    rep = cen.census({"A": {"download_dir": str(dl)}}, db, lf)

    assert rep["orphan_rows"] == 2, (
        f"rows for sites B and ghost are examined by nothing and must be "
        f"counted as such: {rep}")
    assert rep["covered_rows"] + rep["unknown_rows"] + rep["orphan_rows"] \
        == rep["total_done_rows"], f"coverage does not reconcile: {rep}"


def test_an_unresolvable_site_is_unknown_and_says_so(lib):
    """A configured site whose download_dir is absent must not be counted as
    examined -- and must not be silently skipped either."""
    db, lf, dl = lib
    gone = str(dl / "definitely_not_here")
    rep = cen.census({"A": {"download_dir": str(dl)},
                      "C": {"download_dir": gone},
                      "D": {}}, db, lf)

    reasons = {sid: why for sid, _, why in rep["unknown"]}
    assert set(reasons) == {"C", "D"}, rep["unknown"]
    assert "absent" in reasons["C"]
    assert "no download_dir" in reasons["D"]


def test_report_states_coverage_even_when_there_is_no_drift(lib):
    """A clean split over an empty denominator must not read as a clean
    library. This is the whole reason the census prints coverage."""
    db, lf, dl = lib
    rep = cen.census({"Z": {"download_dir": str(dl)}}, db, lf)
    text = cen.format_report(rep)

    assert len(rep["truncations"]) == 0 and len(rep["residue"]) == 0
    assert "rows examined : 0 of 5" in text, text
    assert "not in sites_config : 5" in text, text
    assert "complete -- every done row was examined" not in text, (
        "the report claimed completeness while examining nothing:\n" + text)


# ─── The denominator mismatch (v3.66.827) ─────────────────────────────
#
# The per-site pass calls list_size_drift(dd, site_id=sid), but the panel
# calls audit({download_dir}) with NO site_id (frontend/src/routes/Library.tsx
# :497 -> library_final.audit(), whose site_id is Optional and defaults to
# None), so audit() spans EVERY history row in the directory. A census that
# only ever asks per-site is structurally blind to rows whose site_id is not
# in sites_config -- which on the deploy box was 31 of 31.


def test_whole_history_sweep_sees_a_row_whose_site_is_not_configured(lib):
    """The exact 0-vs-3 case: per-site says clean, the panel's own call does not.

    Site Z is configured and owns the download dir but has ZERO history rows,
    so every per-site figure is 0. The rows actually IN that directory belong
    to A, B and ghost -- none of them configured. list_size_drift with
    site_id=None (what audit() passes) finds three of them, including a real
    -9899 truncation.
    """
    db, lf, dl = lib
    rep = cen.census({"Z": {"download_dir": str(dl)}}, db, lf)

    # the blindness, restated so the failure names the cause
    assert len(rep["truncations"]) == 0 and len(rep["residue"]) == 0, (
        "fixture drift: the per-site pass was supposed to see nothing here")

    trunc = {r["filename"] for r in rep["sweep_truncations"]}
    res = {r["filename"] for r in rep["sweep_residue"]}
    assert trunc == {"short.mp4"}, (
        "the whole-history sweep missed the truncation the panel reports: "
        f"{rep['sweep_truncations']}")
    assert res == {"residue.mp4", "b.mp4"}, (
        f"the whole-history sweep missed residue rows: {rep['sweep_residue']}")
    assert len(rep["sweep_truncations"]) + len(rep["sweep_residue"]) == 3, rep

    worst = min(rep["sweep_truncations"], key=lambda r: r["delta_bytes"])
    assert worst["delta_bytes"] == -9899, worst
    # every swept row carries the directory it was found under, or the
    # operator cannot tell which panel run would show it
    assert all(r.get("_dir") == str(dl)
               for r in rep["sweep_truncations"] + rep["sweep_residue"]), rep


def test_the_sweep_is_reported_alongside_the_per_site_figures(lib):
    """Alongside, not instead of. The split by SIGN is still the decision;
    the sweep answers a DIFFERENT question (what the panel shows) and a
    report that prints only one of them cannot be reconciled with the other."""
    db, lf, dl = lib
    text = cen.format_report(cen.census({"Z": {"download_dir": str(dl)}},
                                        db, lf))

    assert "TRUNCATIONS  (delta<0) : 0" in text, text
    assert "SWEEP" in text, (
        "the whole-history sweep is not in the report at all:\n" + text)
    assert "site_id=None" in text, (
        "the report does not say the sweep is the panel's own call:\n" + text)
    assert str(dl) in text, text


def test_the_rendered_sweep_lines_carry_the_SWEEP_numbers(lib):
    """The report TEXT is the deliverable, and it was not pinned.

    ``format_report`` prints four totals. Nothing read the rendered string, so
    feeding the SWEEP lines the PER-SITE lists -- len(rep["truncations"])
    instead of len(rep["sweep_truncations"]) -- printed 0 truncations while
    the panel-comparable figure was 1, and every test stayed green. That is
    section 0 one level up: the assertions could not see the artifact the
    operator actually reads.

    The fixture is built so the two populations DISAGREE (per-site 0/0, sweep
    1/2). If they were equal this test would prove nothing, so the
    disagreement is asserted first and the numbers are matched LINE-EXACT --
    a substring check cannot distinguish "TRUNCATIONS  (delta<0) : 0" from
    the sweep line that contains the same tail.
    """
    db, lf, dl = lib
    rep = cen.census({"Z": {"download_dir": str(dl)}}, db, lf)

    per_site = (len(rep["truncations"]), len(rep["residue"]))
    sweep = (len(rep["sweep_truncations"]), len(rep["sweep_residue"]))
    assert per_site == (0, 0) and sweep == (1, 2), (
        "fixture drift: this test is only meaningful while the per-site and "
        f"sweep populations differ; got per_site={per_site} sweep={sweep}")

    lines = [ln.rstrip() for ln in cen.format_report(rep).splitlines()]
    text = "\n".join(lines)

    assert "TRUNCATIONS  (delta<0) : 0" in lines, (
        "the per-site truncation line does not carry the per-site "
        "figure:\n" + text)
    assert "ATOM RESIDUE (delta>0) : 0" in lines, (
        "the per-site residue line does not carry the per-site "
        "figure:\n" + text)
    assert "  SWEEP TRUNCATIONS (delta<0) : 1" in lines, (
        "the SWEEP truncation line does not carry the SWEEP figure -- the "
        "panel shows 1 truncation and the report prints another number:\n"
        + text)
    assert "  SWEEP RESIDUE     (delta>0) : 2" in lines, (
        "the SWEEP residue line does not carry the SWEEP figure:\n" + text)

    # the per-directory sweep line must agree with the sweep totals too
    dir_line = [ln for ln in lines if ln.lstrip().startswith(str(dl)[:38])]
    assert dir_line and "trunc 1" in dir_line[0] and "residue 2" in dir_line[0], (
        "the per-directory sweep line disagrees with the sweep totals:\n"
        + text)


def test_a_blank_download_dir_is_examined_under_the_deployment_default(lib):
    """A site with a BLANK download_dir still writes somewhere.

    app.py:2493 _oi_default_download_dir() resolves BD_DOWNLOAD_DIR -> global
    config download_dir -> ~/Downloads, and runner.py:3628-3654 calls it at
    write time. Bucketing such a site UNKNOWN examines nothing while the
    files are on disk under the default.

    This pins the PER-SITE fallback only. The standalone sweep of the default
    dir is a different branch and is pinned separately below -- here the
    default dir reaches the sweep through THIS site, so this fixture is blind
    to that branch by construction.
    """
    db, lf, dl = lib
    rep = cen.census({"A": {}}, db, lf, default_dir=str(dl))

    reasons = {sid for sid, _, _ in rep["unknown"]}
    assert "A" not in reasons, (
        f"a blank download_dir was still bucketed UNKNOWN: {rep['unknown']}")
    assert {r["filename"] for r in rep["truncations"]} == {"short.mp4"}, rep
    assert {r["filename"] for r in rep["residue"]} == {"residue.mp4"}, rep
    assert rep["default_dir"] == str(dl)
    # and the default dir is in the whole-history sweep too
    assert str(dl) in {d for d, _, _, _ in rep["sweep_lines"]}, rep


def test_the_default_dir_is_swept_when_no_configured_site_points_at_it(lib):
    """The standalone default-dir sweep branch, with a denominator that
    contains it.

    WHY THIS FIXTURE IS BUILT THE HARD WAY. The obvious test gives the one
    configured site a BLANK download_dir, so the census substitutes the
    default and appends that directory to ``sweep_sources`` from inside the
    per-site loop. The default dir is then already swept by another route,
    and deleting the standalone branch entirely changes NOTHING -- measured:
    all tests stayed green with it disabled.

    So here the configured site owns its OWN directory (empty, elsewhere) and
    NOTHING configured points at the default. The standalone branch is the
    only way the default dir can enter the sweep at all, which is what makes
    this test able to see its subject.
    """
    db, lf, dl = lib
    elsewhere = Path(tempfile.mkdtemp(prefix="cen_other_"))

    rep = cen.census({"Z": {"download_dir": str(elsewhere)}}, db, lf,
                     default_dir=str(dl))

    # no configured site names the default dir -- so the per-site pass cannot
    # have put it into the sweep
    assert str(dl) not in {dd for _, _, _, dd in rep["lines"]}, (
        f"fixture drift: a configured site points at the default dir: "
        f"{rep['lines']}")
    assert len(rep["truncations"]) == 0 and len(rep["residue"]) == 0, (
        f"fixture drift: the per-site pass was supposed to see nothing: {rep}")

    swept = {dd: srcs for dd, srcs, _, _ in rep["sweep_lines"]}
    assert str(dl) in swept, (
        "the deployment default download dir was NOT swept, so files written "
        "by the runner's no-dl-dir branch were examined by nothing: "
        f"{rep['sweep_lines']}")
    assert "<deployment default>" in swept[str(dl)], (
        f"the default dir is swept but not labelled as such: {swept}")

    trunc = {r["filename"] for r in rep["sweep_truncations"]}
    assert trunc == {"short.mp4"}, (
        "the sweep of the deployment default missed the truncation: "
        f"{rep['sweep_truncations']}")
    worst = min(rep["sweep_truncations"], key=lambda r: r["delta_bytes"])
    assert worst["delta_bytes"] == -9899, worst
    assert {r["filename"] for r in rep["sweep_residue"]} \
        == {"residue.mp4", "b.mp4"}, rep["sweep_residue"]


def test_an_unresolvable_default_is_said_so_not_assumed(lib):
    """UNKNOWN is a third state. A default dir that is not a directory must
    not read as 'nothing to sweep there'."""
    db, lf, dl = lib
    gone = str(dl / "no_such_default")
    rep = cen.census({"A": {"download_dir": str(dl)}}, db, lf, default_dir=gone)

    assert gone not in {d for d, _, _, _ in rep["sweep_lines"]}, rep
    assert "absent" in rep["default_dir_state"], rep["default_dir_state"]
    assert gone in cen.format_report(rep)


def test_orphan_site_ids_and_names_are_printed_not_just_counted(lib):
    """The box finding must be reproducible FROM THE TOOL.

    The v3.66.826 closure rested on an ad-hoc query nobody can re-run,
    because the report emitted only a COUNT of orphan rows. A count cannot
    tell an operator that all 23 were `bdseed fixture site`.
    """
    db, lf, dl = lib
    db.db_log(site_id="zz9", site_name="bdseed fixture site", url="u9",
              status="done", filename="z.mp4", file_size=42)
    rep = cen.census({"A": {"download_dir": str(dl)}}, db, lf)

    found = {sid: (name, n) for sid, name, n in rep["orphan_sites"]}
    assert set(found) == {"B", "ghost", "zz9"}, rep["orphan_sites"]
    assert found["zz9"] == ("bdseed fixture site", 1), found
    assert sum(n for _, _, n in rep["orphan_sites"]) == rep["orphan_rows"], rep

    text = cen.format_report(rep)
    assert "zz9" in text and "bdseed fixture site" in text, (
        "orphan site ids/names are not in the report, so the box finding "
        "cannot be reproduced from the tool:\n" + text)


def test_orphan_sites_agree_with_an_independent_recount(lib):
    """Pin what the grouped derivation actually buys.

    MEASURED, AND STATED SO IT IS NOT INHERITED WRONG: ``orphan_rows`` is
    arithmetically IDENTICAL to ``total - covered - unknown_rows``. The
    per-site loop puts every configured site in exactly one of covered or
    unknown, so covered + unknown_rows is exactly the row count of configured
    sites and the remainder is exactly the orphan count -- on every input.
    Reverting that line to subtraction passes this file, and no fixture can
    change that; the coverage reconciliation assertion above is an identity
    about the LOOP's exhaustiveness, not evidence about how the count is
    derived. The source comment now says the same thing instead of claiming
    a distinction nothing tests.

    What subtraction CANNOT produce is the ids and names, so that is what is
    pinned here -- against a recount taken straight from the database rather
    than from another field of the same report.
    """
    db, lf, dl = lib
    configured = {"A": {"download_dir": str(dl)}}
    rep = cen.census(configured, db, lf)

    with db.db_conn() as cx:
        raw = cx.execute(
            "SELECT site_id, site_name, COUNT(*) FROM history "
            "WHERE status='done' AND filename != '' AND file_size > 0 "
            "GROUP BY site_id, site_name").fetchall()
    expected = {(r[0] or "", r[1] or "", r[2]) for r in raw
                if (r[0] or "") not in configured}

    assert set(rep["orphan_sites"]) == expected, (
        "the named orphan list does not match an independent recount of the "
        f"rows whose site_id is not configured: {rep['orphan_sites']} vs "
        f"{sorted(expected)}")
    assert rep["orphan_rows"] == sum(n for _, _, n in expected), rep


def test_the_source_does_not_claim_the_orphan_count_derivation_matters():
    """The claim was untestable and is therefore not allowed back.

    The removed sentence said orphan_rows was "Derived from the grouped rows
    rather than by subtraction", implying a behavioural difference. There is
    none (see above). A claim in the source that nothing can test is read as
    authority, which is exactly how this census shipped a false docstring
    once already.
    """
    src = (_REPO / "tools" / "census_file_size_drift.py").read_text(
        encoding="utf-8")
    assert "Derived from the grouped rows rather than by subtraction" \
        not in src, (
        "the untested derivation claim is back in census_file_size_drift.py; "
        "orphan_rows is arithmetically identical to total - covered - "
        "unknown_rows and no test can distinguish the two forms")


def test_the_docstring_does_not_claim_the_per_site_figures_match_the_panel():
    """The claim was measured FALSE and nothing pinned it.

    The per-site pass and the panel ask different questions; only the sweep
    matches the panel. A docstring that says otherwise is read as authority.
    """
    doc = cen.__doc__ or ""
    assert "The figures then match what the Library panel actually shows" \
        not in doc, ("the false claim is back in the census docstring; the "
                     "per-site figures do NOT match the panel -- the panel "
                     "calls audit() with no site_id")
    assert "site_id=None" in doc, (
        "the docstring must state which call actually matches the panel")


def test_the_update_history_figure_is_re_derived_not_quoted():
    """The shipped docstring said 8; the executable count is 7.

    INSTRUMENT: AST (`ast.Constant` string nodes plus the literal parts of
    `ast.JoinedStr`) over `git ls-files -- bulk_downloader/*.py`, with
    module/class/function docstring nodes structurally excluded so prose
    cannot inflate the count.

    PREDICATE: ``UPDATE\\s+history\\b``. The trailing \\b is the whole
    subject fix -- `_` is a word character, so it excludes
    `UPDATE history_tags` (tags.py:251), which is the DIFFERENT TABLE that
    was miscounted as the 8th site.

    THE file_size CHECK'S OWN DENOMINATOR. It used to read only
    ``splitlines()[node.lineno - 1]``. ``ast.Constant.lineno`` is the START
    line of a multi-line string, and two of the seven live sites already span
    more than one line (batch_ops.py's triple-quoted statement and
    retention.py's implicit concatenation), so an ``UPDATE history SET ...
    file_size`` whose column name landed on the second line was invisible:
    measured, adding ``file_size = 0`` to line 2 of the batch_ops statement
    left all tests green. The subject is now the constant's OWN VALUE (which
    is what the predicate matched, and which folds implicit concatenation)
    UNION the node's full source span lineno..end_lineno.
    """
    import ast
    import re
    import subprocess

    files = subprocess.run(
        ["git", "ls-files", "--", "bulk_downloader/*.py"],
        cwd=str(_REPO), capture_output=True, text=True, check=True
    ).stdout.split()
    assert len(files) > 50, f"denominator collapsed: {len(files)} files"

    pat = re.compile(r"UPDATE\s+history\b", re.I)
    sites = []          # (rel, lineno, end_lineno, constant_text)
    for rel in files:
        src = (_REPO / rel).read_text(encoding="utf-8")
        tree = ast.parse(src)
        docs = set()
        for n in ast.walk(tree):
            body = getattr(n, "body", None)
            if isinstance(n, (ast.Module, ast.FunctionDef, ast.AsyncFunctionDef,
                              ast.ClassDef)) and body \
                    and isinstance(body[0], ast.Expr) \
                    and isinstance(body[0].value, ast.Constant) \
                    and isinstance(body[0].value.value, str):
                docs.add(id(body[0].value))
        for n in ast.walk(tree):
            if isinstance(n, ast.Constant) and isinstance(n.value, str) \
                    and id(n) not in docs and pat.search(n.value):
                sites.append((rel, n.lineno, n.end_lineno or n.lineno, n.value))
            elif isinstance(n, ast.JoinedStr):
                txt = "".join(v.value for v in n.values
                              if isinstance(v, ast.Constant)
                              and isinstance(v.value, str))
                if pat.search(txt):
                    sites.append((rel, n.lineno, n.end_lineno or n.lineno, txt))

    labels = sorted("%s:%d-%d" % (rel, a, b) for rel, a, b, _ in sites)
    stated = re.search(r"\((\d+)\s+`UPDATE history` sites", cen.__doc__ or "")
    assert stated, "the census docstring no longer states the figure at all"
    assert int(stated.group(1)) == len(sites), (
        f"the docstring says {stated.group(1)} `UPDATE history` sites; the "
        f"AST count is {len(sites)}: {labels}")

    # A multi-line statement's lineno is only its FIRST line -- read the whole
    # span, and the constant's own value, or the check cannot see its subject.
    assert len(sites) == len(labels), "duplicate site labels"
    offenders = []
    for rel, lineno, end_lineno, text in sites:
        span = "\n".join((_REPO / rel).read_text(encoding="utf-8")
                         .splitlines()[lineno - 1:end_lineno])
        if "file_size" in text or "file_size" in span:
            offenders.append("%s:%d-%d" % (rel, lineno, end_lineno))
    assert not offenders, (
        "an UPDATE history site now touches file_size -- the premise the "
        f"whole census rests on has changed: {offenders} (all sites: "
        f"{labels})")
    # the widening is only real if some site actually spans >1 line; if that
    # stops being true the test silently reverts to the narrow check
    assert any(b > a for _, a, b, _ in sites), (
        "no UPDATE history site spans multiple lines any more, so this test "
        "can no longer demonstrate that it reads past the first line; "
        f"re-derive before trusting it: {labels}")


def test_the_residue_distribution_is_printed_for_the_population_that_has_residue(lib):
    """The honesty check was gated on the WRONG population.

    `residue bytes min/median/max` and `residue over 64KB (NOT atom-shaped)`
    are the two lines that decide whether a positive delta is the ~1-2 KB atom
    residue a one-shot re-stat may touch, or something larger it must not.
    Both were emitted only ``if rep["residue"]`` -- the PER-SITE list.

    On the deploy box the per-site pass examined 0 of 31 rows while the
    whole-history sweep found 27 residue rows, so the two decision lines were
    structurally unreachable in exactly the case that HAS residue. Section 0,
    applied to the honesty check itself: the guard could not see its subject.

    The fixture is built so the per-site residue is EMPTY and the sweep
    residue is not -- the box's own shape. That disagreement is asserted
    first, because if the two populations ever coincide this test proves
    nothing.
    """
    db, lf, dl = lib
    rep = cen.census({"Z": {"download_dir": str(dl)}}, db, lf)

    assert not rep["residue"] and rep["sweep_residue"], (
        "fixture drift: this test is only meaningful while the PER-SITE "
        "residue is empty and the SWEEP residue is not; got per_site="
        f"{len(rep['residue'])} sweep={len(rep['sweep_residue'])}")

    text = cen.format_report(rep)
    sizes = sorted(abs(r["delta_bytes"]) for r in rep["sweep_residue"])
    expected = "SWEEP residue bytes min/median/max : %d / %d / %d" % (
        sizes[0], sizes[len(sizes) // 2], sizes[-1])

    assert expected in text, (
        "the sweep residue distribution was not printed, so an operator "
        "reading this report cannot tell atom-shaped residue from a large "
        f"delta a re-stat must not touch:\n{text}")
    assert "SWEEP residue over 64KB (NOT atom-shaped)" in text, (
        "the over-64KB honesty check is absent for the sweep population:\n"
        + text)


# ─── Coverage counted what was COMPARED, not what was queried (v3.66.845) ──
#
# The census counted coverage by DB row count (`covered += n`) while
# library_final's resolver silently drops any row whose recorded basename does
# not resolve to exactly one on-disk file, plus any resolved path that cannot
# be stat'ed. Dropped rows were reported as examined, so the tool reported
# clean over a denominator that structurally excluded the rows it failed to
# look at -- and the whole-history sweep printed drift counts with no
# examined-of-total at all, making "0 of 5 resolved" render identically to
# "swept and clean".
#
# WHOLE-LINE assertions below, deliberately. The obvious `"rows examined : 4 of
# 5" in text` also matches the NEW per-directory and SWEEP lines on this
# fixture, so a mutant that fixed only the sweep line would pass it. The
# file's own docstring records that trap; these are the same trap one release
# later.


def _line(text, prefix):
    """The single rstripped line starting with `prefix`, or None."""
    hits = [ln.rstrip() for ln in text.splitlines() if ln.startswith(prefix)]
    assert len(hits) <= 1, f"{prefix!r} matched {len(hits)} lines: {hits}"
    return hits[0] if hits else None


def test_a_row_that_never_resolved_is_not_counted_as_examined(lib):
    """The register's first reproduction, at the fixture's own scale.

    Every one of the 5 rows is attributed to a directory the census sweeps, so
    `covered` is 5 -- but `g.mp4` does not exist on disk and is never compared.
    Coverage must say 4, and the report must not claim completeness.
    """
    db, lf, dl = lib
    rep = cen.census({"A": {"download_dir": str(dl)},
                      "B": {"download_dir": str(dl)},
                      "ghost": {"download_dir": str(dl)}}, db, lf)
    text = cen.format_report(rep)

    assert rep["covered_rows"] == 5, (
        "fixture drift: this test is only meaningful while all 5 rows are "
        f"attributed to a swept dir; got {rep['covered_rows']}")
    assert rep["examined_rows"] == 4, (
        "g.mp4 has no file on disk, so it was never compared -- but coverage "
        f"counted it. examined_rows={rep['examined_rows']}\n{text}")
    assert _line(text, "COVERAGE  rows examined : ") == \
        "COVERAGE  rows examined : 4 of 5", (
        "the COVERAGE line reports the queried row count, not the compared "
        f"one:\n{text}")
    assert "complete -- every done row was examined" not in text, (
        "the report claimed every row was examined while one never "
        f"resolved:\n{text}")


def test_the_uncompared_rows_are_named_with_a_reason(lib):
    """A count of misses nobody can act on is only half the fix."""
    db, lf, dl = lib
    rep = cen.census({"A": {"download_dir": str(dl)},
                      "B": {"download_dir": str(dl)},
                      "ghost": {"download_dir": str(dl)}}, db, lf)
    text = cen.format_report(rep)

    assert rep["uncompared_rows"] == 1, rep["uncompared_rows"]
    ln = _line(text, "          rows attributed but NEVER COMPARED : ")
    assert ln, f"the uncompared rows are not named at all:\n{text}"
    assert "absent" in ln, (
        "the reason histogram does not say WHY the row was not compared, so "
        f"an operator cannot act on it: {ln!r}")
    assert _line(text, "          rows attributed to a swept directory : ") == \
        "          rows attributed to a swept directory : 5", (
        "the old covered_rows figure is gone rather than relabelled -- keep "
        f"it readable, just stop calling it 'examined':\n{text}")


def test_a_sweep_that_resolved_nothing_is_unknown_not_clean(lib):
    """The register's second reproduction.

    A directory where nothing resolves prints 0 truncations and 0 residue --
    byte-identical to a directory that was swept and is genuinely clean. The
    sweep must carry its own examined-of-total and say which it is.
    """
    db, lf, dl = lib
    empty = Path(tempfile.mkdtemp(prefix="cen_empty_"))
    rep = cen.census({"A": {"download_dir": str(empty)}}, db, lf)
    text = cen.format_report(rep)

    assert not rep["sweep_truncations"] and not rep["sweep_residue"], (
        "fixture drift: this test needs a sweep with zero drift so that the "
        "only thing distinguishing it from clean is the coverage line")
    assert rep["sweep_examined_rows"] == 0, rep["sweep_examined_rows"]
    assert _line(text, "  SWEEP rows examined : ") == \
        "  SWEEP rows examined : 0 of 5", (
        f"the sweep printed no examined-of-total:\n{text}")
    assert "SWEEP EXAMINED NOTHING" in text, (
        "a sweep that compared nothing rendered identically to a clean "
        f"one:\n{text}")
    assert "UNKNOWN, not clean" in text, text


def test_the_completeness_line_is_still_printed_when_it_is_true(lib):
    """The green side. Without this, deleting the line passes the whole band.

    Every other assertion here is about the line being ABSENT, so a mutant
    that simply never emits it satisfies all of them. This is the only test
    that fails on that mutant.
    """
    db, lf, dl = lib
    # Give every row a real file, so examined == total == 5.
    (dl / "g.mp4").write_bytes(b"\0" * 333)
    rep = cen.census({"A": {"download_dir": str(dl)},
                      "B": {"download_dir": str(dl)},
                      "ghost": {"download_dir": str(dl)}}, db, lf)
    text = cen.format_report(rep)

    assert rep["examined_rows"] == rep["total_done_rows"] == 5, (
        f"examined={rep['examined_rows']} total={rep['total_done_rows']}\n{text}")
    assert "complete -- every done row was examined" in text, (
        "every row WAS examined and the report did not say so -- the "
        f"completeness line is never emitted:\n{text}")
    assert "SWEEP complete" in text, text


# --- The units the coverage figures are counted in (v3.66.845, review) ----
#
# Every figure below was measured wrong before these tests existed:
#   * the per-directory `examined N of M` was a pure no-op -- printing
#     `considered` in its place, or deleting the field, passed all 24 tests;
#   * SWEEP TRUNCATIONS/RESIDUE counted (row, directory) PAIRS while
#     `SWEEP rows examined` counted ROWS, so "examined 2 of 2" sat above
#     "SWEEP TRUNCATIONS : 2" for ONE truncated file on disk;
#   * the `reasons:` histogram was summed over directories: "absent 15"
#     printed directly under "0 of 5";
#   * a history read that RAISED rendered as "0 of N rows resolved to exactly
#     one file" -- a cause nobody measured;
#   * the SWEEP PARTIAL arm of the three-way verdict, and the whole
#     denominator-mismatch mechanism, were unpinned.
#
# TWO SWEPT DIRECTORIES IS THE NORMAL CONFIGURATION, not an edge case:
# census() adds the deployment default to sweep_sources unconditionally when
# it resolves, and _basename_index rglobs, so a site dir nested under the
# download root resolves the same history row twice.


def test_the_per_directory_sweep_line_carries_EXAMINED_not_CONSIDERED(lib):
    """The per-directory examined-of-total must be the examined figure.

    RED-proving mutants: printing `_sc["considered"]` in place of
    `_sc["examined"]`, and deleting the field entirely, both passed the whole
    file before this test. The fixture forces the two apart -- the swept dir
    is EMPTY, so considered is 5 and examined is 0.
    """
    db, lf, dl = lib
    empty = Path(tempfile.mkdtemp(prefix="cen_pdir_"))
    rep = cen.census({"A": {"download_dir": str(empty)}}, db, lf)
    sc = rep["sweep_coverage"][str(empty)]
    assert (sc["considered"], sc["examined"]) == (5, 0), (
        f"fixture drift: this test needs considered != examined; got {sc}")

    lines = [ln.rstrip() for ln in cen.format_report(rep).splitlines()]
    hit = [ln for ln in lines if ln.lstrip().startswith(str(empty)[:38])]
    assert len(hit) == 1, f"per-directory sweep line not found: {lines}"
    assert "examined 0 of 5" in hit[0], (
        "the per-directory sweep line reports the QUERIED count, not the "
        f"compared one: {hit[0]!r}")


def test_the_sweep_totals_are_per_ROW_like_the_examined_figure(lib):
    """The unit the register's own reproduction got wrong.

    `sweep_examined_rows` is a UNION of row ids; SWEEP TRUNCATIONS/RESIDUE
    append one entry per (row, directory). A site dir nested under the
    deployment default resolves every row twice, so the totals doubled while
    the examined figure did not -- and the report printed them adjacent.

    ONE file on disk is truncated. The report must say ONE.
    """
    db, lf, dl = lib
    # the site writes into dl/sub, which the deployment default (dl) rglobs --
    # the ordinary production layout, not a contrivance
    rep = cen.census({"A": {"download_dir": str(dl / "sub")}}, db, lf,
                     default_dir=str(dl))

    dirs = sorted(rep["sweep_coverage"])
    assert dirs == [str(dl), str(dl / "sub")], (
        f"fixture drift: this test needs the site dir nested under the "
        f"swept default; got {dirs}")
    assert rep["sweep_multi_dir_rows"] == 1, (
        "fixture drift: residue.mp4 must resolve under BOTH swept dirs or "
        f"this test cannot see its subject; got {rep['sweep_multi_dir_rows']}")

    assert len(rep["sweep_truncations"]) == 1, (
        "the sweep counted (row, directory) pairs: exactly one file on disk "
        f"is truncated: {rep['sweep_truncations']}")
    assert len(rep["sweep_residue"]) == 2, (
        "residue.mp4 resolves under dl AND dl/sub and was counted twice -- "
        "two files on disk carry positive drift, not three: "
        f"{[r['filename'] for r in rep['sweep_residue']]}")
    assert len(rep["sweep_truncations"]) + len(rep["sweep_residue"]) \
        <= rep["sweep_examined_rows"], (
        "more drift findings than rows examined -- the two figures are in "
        f"different units: {rep['sweep_examined_rows']} examined vs "
        f"{len(rep['sweep_truncations']) + len(rep['sweep_residue'])} findings")

    text = cen.format_report(rep)
    assert "duplicate (row, directory) drift entr" in text, (
        "the per-directory lines and the totals disagree and the report does "
        f"not say why:\n{text}")


def test_the_sweep_reason_histogram_sums_to_the_figure_it_explains(lib):
    """`reasons:` is printed directly under "0 of N". It must add up to N.

    Summed per directory it counted (row, directory) pairs -- measured
    "absent 15" under "0 of 5" with three swept dirs -- and it also reported
    a row as a miss when another directory had compared it.
    """
    db, lf, dl = lib
    # d1 sees nothing at all; d2 sees g.mp4 under TWO names, so the same row
    # is "absent" under one dir and "ambiguous" under the other. Both the
    # per-directory sum AND a naive per-state union double-count it.
    d1 = Path(tempfile.mkdtemp(prefix="cen_r1_"))
    d2 = Path(tempfile.mkdtemp(prefix="cen_r2_"))
    (d2 / "x").mkdir()
    (d2 / "y").mkdir()
    (d2 / "x" / "g.mp4").write_bytes(b"\0" * 333)
    (d2 / "y" / "g.mp4").write_bytes(b"\0" * 999)
    rep = cen.census({"A": {"download_dir": str(d1)},
                      "B": {"download_dir": str(d2)}}, db, lf)

    assert sorted(rep["sweep_coverage"]) == sorted([str(d1), str(d2)]), (
        f"fixture drift: needs both dirs swept; got {sorted(rep['sweep_coverage'])}")
    assert rep["sweep_coverage"][str(d2)]["states"].get("ambiguous") == 1, (
        "fixture drift: g.mp4 must be AMBIGUOUS under d2 and absent under d1, "
        f"or the two histograms agree and this test proves nothing: "
        f"{rep['sweep_coverage'][str(d2)]['states']}")
    assert rep["sweep_examined_rows"] == 0, rep["sweep_examined_rows"]
    assert sum(rep["sweep_states"].values()) == rep["sweep_considered"], (
        "the reason histogram does not sum to the population it explains -- "
        f"{rep['sweep_states']} over {rep['sweep_considered']} rows")
    assert rep["sweep_states"] == {"ambiguous": 1, "absent": 4}, (
        "a row that is absent under one directory and ambiguous under another "
        f"is ONE uncompared row, not one of each: {rep['sweep_states']}")

    text = cen.format_report(rep)
    assert "  reasons: absent 4, ambiguous 1" in \
        [ln.rstrip() for ln in text.splitlines()], (
        f"the reasons line is in (row, directory) units:\n{text}")


def test_a_partially_swept_population_says_PARTIAL(lib):
    """The middle arm of the three-way verdict.

    NOTHING and complete are both pinned; deleting the PARTIAL branch passed
    the whole file. A sweep that compared 4 of 5 must say so -- it is the
    commonest of the three states and the one a clean-looking report hides.
    """
    db, lf, dl = lib
    rep = cen.census({"A": {"download_dir": str(dl)}}, db, lf)
    assert (rep["sweep_examined_rows"], rep["sweep_considered"]) == (4, 5), (
        f"fixture drift: needs a partial sweep; got "
        f"{rep['sweep_examined_rows']} of {rep['sweep_considered']}")

    text = cen.format_report(rep)
    assert "SWEEP PARTIAL -- 4 of 5 rows were compared" in text, (
        f"a partial sweep did not say it was partial:\n{text}")
    assert "SWEEP complete" not in text and "SWEEP EXAMINED NOTHING" not in text, (
        f"a partial sweep also claimed one of the other two verdicts:\n{text}")


def test_a_row_that_resolved_but_could_not_be_statted_is_named(lib):
    """`stat_failed` was incremented and never surfaced.

    Deleting the counter passed the whole file: no fixture produced a stat
    failure. The subject is the ACCOUNTING, not the filesystem, so the failure
    is injected -- as root every chmod-based attempt succeeds anyway.
    """
    db, lf, dl = lib
    real = lf.os.path.getsize

    def boom(p):
        if str(p).endswith("short.mp4"):
            raise OSError(5, "injected I/O error")
        return real(p)

    lf.os.path.getsize = boom
    try:
        rep = cen.census({"A": {"download_dir": str(dl)}}, db, lf)
        text = cen.format_report(rep)
    finally:
        lf.os.path.getsize = real

    sc = rep["site_coverage"]["A"]
    assert sc["stat_failed"] == 1, (
        f"a resolved path that could not be stat'ed was not counted: {sc}")
    assert sc["examined"] + sum(sc["states"].values()) + sc["stat_failed"] \
        == sc["considered"], (
        f"the scan's own accounting does not reconcile: {sc}")
    assert "stat failed 1" in text, (
        "a row that resolved and then could not be stat'ed is missing from "
        f"the reason histogram, so the breakdown does not add up:\n{text}")


def test_a_history_read_that_raised_is_not_reported_as_a_resolution_failure(lib):
    """`query_failed` was set by the scan and read by nobody.

    With the DB read raising, the report asserted "0 of N rows resolved to
    exactly one file under any swept directory" -- UNKNOWN correctly, but for
    a cause it had not measured, and with the reasons line suppressed because
    the histogram was empty. Naming the wrong cause is section 0 in a
    sentence.
    """
    db, lf, dl = lib
    real_scan = lf.size_drift_scan

    class Failing:
        @staticmethod
        def size_drift_scan(dd, **kw):
            r = real_scan(dd, **kw)      # keep the shape honest
            return {**r, "rows": [], "considered": 0, "examined": 0,
                    "states": {}, "state_ids": {}, "stat_failed": 0,
                    "examined_ids": set(), "query_failed": True}

    rep = cen.census({"A": {"download_dir": str(dl)}}, db, Failing)
    text = cen.format_report(rep)

    assert rep["query_failed_dirs"] == [str(dl)], rep["query_failed_dirs"]
    assert rep["query_failed_sites"] == ["A"], rep["query_failed_sites"]
    assert "SWEEP READ FAILED" in text, (
        f"a failed history read is invisible in the report:\n{text}")
    assert "rows resolved to exactly one" not in text, (
        "the report blamed basename resolution for a failure of the DATABASE "
        f"READ -- a cause it did not measure:\n{text}")
    assert "HISTORY READ FAILED" in text, text


def test_a_denominator_mismatch_is_printed_and_blocks_the_completeness_line(lib):
    """The mismatch mechanism was recorded, printed and gated -- and none of
    the three was pinned.

    A falsy site_id is the live trigger: library_final's ``if site_id:`` is
    False for "", so that site's scan sweeps EVERY row while _done_row_counts
    grouped only its own. `examined` then counts (row, scan) pairs and can
    reach the total by coincidence, which is exactly when a completeness
    claim would be false.
    """
    db, lf, dl = lib
    # every row resolves, so `examined` REACHES the total -- which is exactly
    # when a completeness claim would be made, and exactly when it is false.
    (dl / "g.mp4").write_bytes(b"\0" * 333)
    with db.db_conn() as cx:
        cx.execute("UPDATE history SET site_id='' WHERE site_id IN ('A','B')")
    rep = cen.census({"": {"download_dir": str(dl)}}, db, lf)
    text = cen.format_report(rep)

    assert rep["examined_rows"] == rep["total_done_rows"] == 5, (
        "fixture drift: this test is only meaningful while examined reaches "
        f"the total; got {rep['examined_rows']} of {rep['total_done_rows']}")

    _considered = {k: v["considered"] for k, v in rep["site_coverage"].items()}
    assert rep["denominator_mismatches"], (
        "fixture drift: the empty site_id did not produce a mismatch; "
        "per-site considered=%r" % (_considered,))
    assert "DENOMINATOR MISMATCH" in text, (
        f"the mismatch was recorded and never printed:\n{text}")
    assert "(empty site_id)" in text, (
        f"the mismatch line does not name the falsy site id:\n{text}")
    assert "complete -- every done row was examined" not in text, (
        "completeness was claimed while the two denominators disagree -- the "
        f"examined figure is not a row count here:\n{text}")
    assert "NOT a row ratio" in text, (
        f"the COVERAGE ratio is printed without saying its unit changed:\n{text}")
    # NOT `uncompared_rows == sum(site_states.values())` -- that is a
    # TAUTOLOGY: uncompared_rows is DEFINED as that sum, so it holds for any
    # implementation, correct or not. Assert against the POPULATION instead,
    # which is an independent quantity.
    assert rep["uncompared_rows"] <= rep["total_done_rows"], (
        f"uncompared_rows ({rep['uncompared_rows']}) exceeds the whole "
        f"population ({rep['total_done_rows']}) -- the figure is being "
        f"counted in (row x scan) units, not rows: {rep['site_states']}")
    assert rep["examined_rows"] + rep["uncompared_rows"] <= rep["total_done_rows"], (
        f"examined ({rep['examined_rows']}) + uncompared "
        f"({rep['uncompared_rows']}) exceeds the population "
        f"({rep['total_done_rows']}) -- the two figures overlap, so a row is "
        f"being counted as both compared and not compared")



def test_a_row_compared_under_one_dir_is_not_a_miss_under_another(lib):
    """The other half of the sweep's double-count, and the untested one.

    `_merge_state_ids` removes two separate over-counts and only one of them
    was pinned. This is the first: a row that is ABSENT under directory A but
    was COMPARED under directory B is a compared row, full stop. Counting it
    as a miss because one directory could not see it makes the reason
    histogram exceed the number of rows that were actually missed.

    A mutant that drops `claimed = set(examined)` from _merge_state_ids
    survives every other assertion in this file.
    """
    db, lf, dl = lib
    other = Path(tempfile.mkdtemp(prefix="cen_other_"))
    # `other` is swept but holds none of the history filenames, so every row
    # is "absent" there while four of them resolve under `dl`.
    rep = cen.census({"A": {"download_dir": str(dl)},
                      "B": {"download_dir": str(dl)},
                      "ghost": {"download_dir": str(other)}}, db, lf)

    assert len(rep["sweep_coverage"]) >= 2, (
        "fixture drift: this test needs at least two swept directories; got "
        f"{sorted(rep['sweep_coverage'])}")
    swept = rep["sweep_examined_rows"]
    missed = sum(rep["sweep_states"].values())
    assert swept + missed <= rep["sweep_considered"], (
        f"the sweep says it examined {swept} rows and missed {missed}, which "
        f"is more than the {rep['sweep_considered']} rows that exist. A row "
        f"compared under one directory is being counted as a miss under "
        f"another: {rep['sweep_states']}")
    assert swept > 0, (
        "fixture drift: nothing resolved under either directory, so this "
        "test cannot distinguish the double-count it is about")


BD_GATE_SCOPE = "repo-wide"
