"""O1698 c4b-context-parity: the C4 overflow backend must serve local-coder with .137's context, not Ollama's default.

.137 serves local-coder as qwen2.5-coder:7b-16k (num_ctx 16384, same weights as qwen2.5-coder:7b); the C4 serve script
pulled the base tag only, so overflow would truncate prompts the primary accepts. The candidate (harness-work FIX dir,
opt-in via BD_O1698_C4B_CONTEXT_PARITY_CANDIDATE) has bd-c4-context-parity.sh (PARITY | MISMATCH:<field> | COULD-NOT-LOOK,
never PARITY on what it can't judge), Modelfile.local-coder-16k and PATCH-serve.diff for bd-c4-cpu-serve.sh.

Fixtures are the real .137 /api/show bodies (captured read-only 2026-10-03, Ollama 0.34.0, Windows blob paths), trimmed
to the fields the tool reads; the full captures are re-checked when the candidate's evidence/captures dir is present.
"""
import hashlib
import json
import os
from pathlib import Path
import subprocess

import pytest

BD_GATE_SCOPE = "module"
CANDIDATE = os.environ.get("BD_O1698_C4B_CONTEXT_PARITY_CANDIDATE", "")
SERVE_BASE = os.environ.get("BD_O1698_C4B_SERVE_BASE", "")
SERVE_BASE_SHA = "d10317d66375b79b9d9daf840ae04a88e541e63d8209a8a7d34152d98579734b"   # C4d r2 serve.sh (PM 18:52Z; C4d r1 8f20238d superseded)
pytestmark = pytest.mark.skipif(not CANDIDATE, reason="candidate opt-in required")

WEIGHTS = "60e05f2100071479f596b964f89f510f057ce397ea22f2833a0cfe029bfc2463"
OTHER = "f" * 64
WIN_BLOB = "C:\\Users\\Administrator\\.ollama\\models\\blobs\\sha256-"
LINUX_BLOB = "/home/bd/.local/share/bd-c4/models/blobs/sha256-"


def _show(tag, blob=WIN_BLOB + WEIGHTS, num_ctx="16384", parent="qwen2.5-coder:7b"):
    """A /api/show body shaped like .137's: generated-modelfile header (its '# FROM <tag>' is a comment), FROM blob."""
    body = {"modelfile": ('# Modelfile generated by "ollama show"\n'
                          "# To build a new Modelfile based on this, replace FROM with:\n"
                          f"# FROM {tag}\n\nFROM {blob}\nTEMPLATE \"\"\"{{{{ .Prompt }}}}\"\"\"\n"),
            "details": {"parent_model": parent, "format": "gguf", "family": "qwen2", "quantization_level": "Q4_K_M"}}
    if num_ctx is not None:
        body["parameters"] = f"num_ctx                        {num_ctx}"
        body["modelfile"] += f"PARAMETER num_ctx {num_ctx}\n"
    return body


@pytest.fixture
def run(tmp_path):
    tool = Path(CANDIDATE) / "bd-c4-context-parity.sh"
    assert tool.is_file() and os.access(tool, os.X_OK), tool

    def go(primary, overflow, *extra):
        args = [str(tool)]
        for side, body in (("primary", primary), ("overflow", overflow)):
            if body is not None:
                f = tmp_path / f"{side}.json"
                f.write_text(body if isinstance(body, str) else json.dumps(body))
                args += [f"--{side}-json", str(f)]
        r = subprocess.run(args + list(extra), capture_output=True, text=True, timeout=60)
        return r.returncode, r.stdout.strip()
    return go


PRIMARY = _show("qwen2.5-coder:7b-16k")


# ---- RED / GREEN / positive control -----------------------------------------------------------------------------------
def test_base_tag_on_overflow_is_a_num_ctx_mismatch(run):
    """Today's .120 serve set: the base tag, no PARAMETER num_ctx -> Ollama's default context."""
    rc, out = run(PRIMARY, _show("qwen2.5-coder:7b-instruct-q4_K_M", LINUX_BLOB + WEIGHTS, None, ""))
    assert (rc, out.split()[0]) == (1, "MISMATCH:num_ctx"), out
    assert "overflow=num_ctx=default" in out


def test_derived_16k_tag_on_overflow_is_parity(run):
    """Positive control: the probe CAN say yes -- same weights (Linux path) and num_ctx 16384."""
    rc, out = run(PRIMARY, _show("qwen2.5-coder:7b-16k", LINUX_BLOB + WEIGHTS, "16384", "qwen2.5-coder:7b-instruct-q4_K_M"))
    assert (rc, out) == (0, "PARITY num_ctx=16384 weights=" + WEIGHTS[:12])


@pytest.mark.parametrize("overflow,field", [
    (_show("t", LINUX_BLOB + OTHER), "MISMATCH:weights"),
    (_show("t", LINUX_BLOB + OTHER, "8192"), "MISMATCH:num_ctx,weights"),
    (_show("t", LINUX_BLOB + WEIGHTS, "32768"), "MISMATCH:num_ctx"),
], ids=["weights", "both", "bigger-ctx"])
def test_each_differing_field_is_named(run, overflow, field):
    rc, out = run(PRIMARY, overflow)
    assert (rc, out.split()[0]) == (1, field), out


# ---- COULD-NOT-LOOK is never PARITY ------------------------------------------------------------------------------------
NOT_JUDGEABLE = {
    "empty": "",
    "not-json": "<html>502</html>",
    "error-body": {"error": "model 'qwen2.5-coder:7b-16k' not found"},
    "no-modelfile": {"parameters": "num_ctx 16384"},
    "no-digest": {"modelfile": "FROM qwen2.5-coder:7b-instruct-q4_K_M\n", "parameters": "num_ctx 16384"},
    "comment-from-only": {"modelfile": "# FROM " + LINUX_BLOB + WEIGHTS + "\n", "parameters": "num_ctx 16384"},
    "two-digests": {"modelfile": f"FROM {LINUX_BLOB}{WEIGHTS}\nFROM {LINUX_BLOB}{OTHER}\n", "parameters": "num_ctx 16384"},
    "conflicting-ctx": dict(_show("t", LINUX_BLOB + WEIGHTS), parameters="num_ctx 16384\nnum_ctx 4096"),
    "non-int-ctx": dict(_show("t", LINUX_BLOB + WEIGHTS), parameters="num_ctx big"),
    "params-not-text": dict(_show("t", LINUX_BLOB + WEIGHTS), parameters={"num_ctx": 16384}),
}


@pytest.mark.parametrize("body", list(NOT_JUDGEABLE.values()), ids=list(NOT_JUDGEABLE))
def test_unjudgeable_overflow_is_could_not_look(run, body):
    rc, out = run(PRIMARY, body)
    assert rc == 3 and out.startswith("COULD-NOT-LOOK:overflow:"), out


def test_unreachable_primary_is_could_not_look_not_parity(run):
    """A real fetch to a closed loopback port: the http path fails closed."""
    rc, out = run(None, _show("t", LINUX_BLOB + WEIGHTS), "--primary", "127.0.0.1:9")
    assert rc == 3 and out.startswith("COULD-NOT-LOOK:primary:http 127.0.0.1:9"), out


@pytest.mark.parametrize("args", [["--overflow-tag", "x'; rm -rf ~"], ["--primary-via", "ftp"], ["--bogus"],
                                  ["--overflow", "10.0.70.120"]])
def test_bad_arguments_are_usage_errors_before_any_fetch(run, args):
    rc, out = run(PRIMARY, PRIMARY, *args)
    assert rc == 2 and out == ""


def test_full_real_captures_when_present(run):
    captures = Path(CANDIDATE) / "evidence" / "captures"
    if not captures.is_dir():
        pytest.skip("no real captures beside the candidate")
    p = (captures / "show-qwen2.5-coder_7b-16k.json").read_text()
    b = (captures / "show-qwen2.5-coder_7b.json").read_text()
    assert run(p, b)[1].startswith("MISMATCH:num_ctx primary=num_ctx=16384,weights=60e05f210007 overflow=num_ctx=default")
    assert run(p, p) == (0, "PARITY num_ctx=16384 weights=60e05f210007")


# ---- the Modelfile and the serve-script diff --------------------------------------------------------------------------
def _modelfile_lines():
    text = (Path(CANDIDATE) / "Modelfile.local-coder-16k").read_text()
    return [line for line in text.splitlines() if line.strip() and not line.startswith("#")]


def test_modelfile_derives_16k_from_the_pulled_base_tag():
    assert _modelfile_lines() == ["FROM qwen2.5-coder:7b-instruct-q4_K_M", "PARAMETER num_ctx 16384"]


def _patched_render(tmp_path, model):
    base = Path(SERVE_BASE)
    assert hashlib.sha256(base.read_bytes()).hexdigest() == SERVE_BASE_SHA, "serve base drifted: rebase PATCH-serve.diff"
    work = tmp_path / "serve"
    work.mkdir()
    (work / base.name).write_bytes(base.read_bytes())
    patch = (Path(CANDIDATE) / "PATCH-serve.diff").read_text()
    subprocess.run(["patch", "-s", "-p1", "-d", str(work)], input=patch, text=True, check=True, timeout=30)
    (tmp_path / "place.tsv").write_text("10.0.70.120\tESXI01\n")
    (tmp_path / "census.tsv").write_text("host\tstatus\tidle_p95\tmem_available_bytes\n10.0.70.120\tFOUND\t32.0\t33930000000\n")
    r = subprocess.run(["bash", str(work / base.name), "10.0.70.120", "--model", model, "--placement", str(tmp_path / "place.tsv"),
                        "--census", str(tmp_path / "census.tsv"), "--ollama-tarball", "/nonexistent", "--ollama-sha256", "a" * 64,
                        "--expect-weights", WEIGHTS, "--render"], capture_output=True, text=True, timeout=60)
    assert r.returncode == 0, r.stderr
    subprocess.run(["bash", "-n"], input=r.stdout, text=True, check=True, timeout=30)
    return r.stdout


@pytest.mark.skipif(not SERVE_BASE, reason="BD_O1698_C4B_SERVE_BASE (the C4 serve script) not given")
def test_patched_serve_creates_checks_and_serves_the_16k_tag(tmp_path):
    out = _patched_render(tmp_path, "qwen2.5-coder:7b-q4")
    pull, create = out.index("ollama\" pull qwen2.5-coder:7b-instruct-q4_K_M"), out.index("create qwen2.5-coder:7b-16k")
    assert pull < out.index("C4_SERVE_WEIGHTS_MISMATCH") < create            # derive only from verified weights
    line = next(x for x in out.splitlines() if "printf" in x and "Modelfile.local-coder-16k" in x)
    written = line.split("printf '", 1)[1].split("'", 1)[0].replace("%s", "qwen2.5-coder:7b-instruct-q4_K_M")
    assert written.split("\\n")[:2] == _modelfile_lines()                    # the reviewed Modelfile, byte for byte
    assert f'[ "$ctx" != 16384 ] || [ "$derived" != "{WEIGHTS}" ]' in out and "C4_SERVE_CONTEXT_MISMATCH" in out
    assert "model=qwen2.5-coder:7b-16k base=qwen2.5-coder:7b-instruct-q4_K_M" in out


@pytest.mark.skipif(not SERVE_BASE, reason="BD_O1698_C4B_SERVE_BASE (the C4 serve script) not given")
def test_patched_serve_leaves_bge_m3_untouched(tmp_path):
    out = _patched_render(tmp_path, "bge-m3")
    assert '[ "bge-m3:latest" != "bge-m3:latest" ]' in out and "model=bge-m3:latest base=bge-m3:latest" in out
