"""The size-drift census must read the shape the app actually writes.

THE DEFECT THIS PINS. A hand-written version of this census (recorded in
project-knowledge/SESSION_CARRY.md) parsed sites_config.json as
``json.load(...).get("sites", {})``. The file is a FLAT {site_id: cfg}
mapping -- app.py:1276 writes ``{sid: dict(cfg)}`` and app.py:1334 iterates
``data.items()`` -- so that lookup could only ever return empty, and the
census reported a library it had never opened.

WHY THE ORIGINAL'S TEST DID NOT CATCH IT. It was tested against a synthetic
fixture built by hand in the same wrong shape, so the fixture encoded the
author's assumption rather than the app's behaviour. Section 0, one level up:
the denominator excluded the subject and the check reported clean.

SO THE FIXTURE HERE IS WRITTEN BY app.py ITSELF. `_save_sites_config` is the
one function that produces this file in production; driving it makes the app
the oracle, which is the only version of this test that cannot drift back.
A test that hand-builds the JSON would be re-asserting the belief under test.

The remaining tests cover the reason the census exists at all: the SPLIT by
sign, and the coverage accounting that stops a 0/0 result from reading as a
clean library when nothing was examined.
"""
from __future__ import annotations

import json
import os
import sys
import tempfile
from pathlib import Path

import pytest

_REPO = Path(__file__).resolve().parents[1]
if str(_REPO) not in sys.path:
    sys.path.insert(0, str(_REPO))

from tools import census_file_size_drift as cen  # noqa: E402


@pytest.fixture
def lib(clean_workdir):
    """A download dir with an intact file, a truncated one, and a residue one,
    plus history rows for two sites sharing that directory and one orphan row
    whose site is not in any config."""
    import bulk_downloader.db as db
    from bulk_downloader import library_final as lf

    saved = db.DB_PATH
    db.DB_PATH = os.path.join(tempfile.mkdtemp(prefix="cen_db_"), "q.db")
    db.db_init()

    dl = Path(tempfile.mkdtemp(prefix="cen_dl_"))
    (dl / "sub").mkdir()
    (dl / "intact.mp4").write_bytes(b"\0" * 5000)
    (dl / "short.mp4").write_bytes(b"\0" * 100)       # recorded 9999 -> -9899
    (dl / "sub" / "residue.mp4").write_bytes(b"\0" * 8233)  # recorded 7000 -> +1233
    (dl / "b.mp4").write_bytes(b"\0" * 200)           # recorded 100   -> +100

    rows = [("A", "u1", "intact.mp4", 5000), ("A", "u2", "short.mp4", 9999),
            ("A", "u3", "residue.mp4", 7000), ("B", "u4", "b.mp4", 100),
            ("ghost", "u5", "g.mp4", 333)]
    for sid, url, fn, sz in rows:
        db.db_log(site_id=sid, site_name=sid, url=url, status="done",
                  filename=fn, file_size=sz)
    try:
        yield db, lf, dl
    finally:
        db.DB_PATH = saved


def _write_config_via_the_app(tmp_path, sites):
    """Produce sites_config.json using app.py's OWN writer.

    This is the point of the test: the fixture must be generated by the code
    that generates it in production, not hand-rolled to match a belief.
    """
    from bulk_downloader import app as bd_app

    target = Path(tmp_path) / "sites_config.json"
    saved_file, saved_cfg = bd_app.SITES_FILE, dict(bd_app.s_cfg)
    try:
        bd_app.SITES_FILE = target
        bd_app.s_cfg.clear()
        bd_app.s_cfg.update(sites)
        bd_app._save_sites_config()
    finally:
        bd_app.SITES_FILE = saved_file
        bd_app.s_cfg.clear()
        bd_app.s_cfg.update(saved_cfg)
    assert target.is_file(), "app._save_sites_config wrote no file"
    return target


def test_census_reads_the_shape_the_app_actually_writes(tmp_path):
    """RED against a ``.get("sites", {})`` reader: it returns {} here."""
    target = _write_config_via_the_app(
        tmp_path, {"s1": {"name": "wow", "download_dir": "/some/where"}})

    sites, ignored = cen.load_sites(str(target))

    assert set(sites) == {"s1"}, (
        f"the census did not find the site the app wrote: {sites!r}. The file "
        f"is a flat {{site_id: cfg}} mapping, not {{'sites': ...}}")
    assert sites["s1"].get("download_dir") == "/some/where"
    assert ignored == []


def test_the_written_file_has_no_sites_wrapper(tmp_path):
    """State the trap directly, so the failure names the cause.

    Without this, the test above still passes if someone 'helpfully' makes
    load_sites accept BOTH shapes -- and the register's wrong command would
    then look correct again.
    """
    target = _write_config_via_the_app(tmp_path, {"s1": {"name": "wow"}})
    raw = json.loads(target.read_text(encoding="utf-8"))

    assert "sites" not in raw or isinstance(raw.get("sites"), dict) and "s1" in raw, (
        "app.py wrote a 'sites' wrapper; the census's flat reader is now wrong")
    assert "s1" in raw, f"top-level keys are site ids; got {sorted(raw)}"


def test_a_non_mapping_config_is_refused_not_treated_as_empty():
    """UNKNOWN is a third state. An unusable config must raise, because the
    alternative -- an empty site set -- reports a spotless library."""
    p = Path(tempfile.mkdtemp(prefix="cen_bad_")) / "sites_config.json"
    p.write_text('["not", "a", "mapping"]', encoding="utf-8")
    with pytest.raises(cen.CensusError):
        cen.load_sites(str(p))

    p.write_text("{not json", encoding="utf-8")
    with pytest.raises(cen.CensusError):
        cen.load_sites(str(p))


def test_drift_is_split_by_sign_not_totalled(lib):
    """The split IS the decision: a truncation and residue must not merge."""
    db, lf, dl = lib
    rep = cen.census({"A": {"download_dir": str(dl)}}, db, lf)

    trunc = {r["filename"]: r for r in rep["truncations"]}
    res = {r["filename"]: r for r in rep["residue"]}
    assert "short.mp4" in trunc, f"truncation not reported: {rep['truncations']}"
    assert trunc["short.mp4"]["delta_bytes"] == -9899
    assert "residue.mp4" in res, f"residue not reported: {rep['residue']}"
    assert res["residue.mp4"]["delta_bytes"] == 1233
    assert "intact.mp4" not in trunc and "intact.mp4" not in res, (
        "an intact file was reported as drifted")


def test_two_sites_sharing_a_download_dir_are_both_examined(lib):
    """The dedupe bug the register's version shipped.

    list_size_drift filters by site_id, so skipping an already-seen
    download_dir drops that site's rows entirely instead of avoiding work.
    """
    db, lf, dl = lib
    rep = cen.census({"A": {"download_dir": str(dl)},
                      "B": {"download_dir": str(dl)}}, db, lf)

    assert {r["filename"] for r in rep["residue"]} >= {"b.mp4"}, (
        "site B shares A's download_dir and was skipped; its rows were never "
        f"examined: {rep['residue']}")
    assert rep["covered_rows"] == 4, rep


def test_rows_whose_site_is_gone_are_reported_not_silently_dropped(lib):
    """The deploy box's actual state: every done row belonged to a site that
    no longer exists, so a 0/0 result meant 'examined nothing'."""
    db, lf, dl = lib
    rep = cen.census({"A": {"download_dir": str(dl)}}, db, lf)

    assert rep["orphan_rows"] == 2, (
        f"rows for sites B and ghost are examined by nothing and must be "
        f"counted as such: {rep}")
    assert rep["covered_rows"] + rep["unknown_rows"] + rep["orphan_rows"] \
        == rep["total_done_rows"], f"coverage does not reconcile: {rep}"


def test_an_unresolvable_site_is_unknown_and_says_so(lib):
    """A configured site whose download_dir is absent must not be counted as
    examined -- and must not be silently skipped either."""
    db, lf, dl = lib
    gone = str(dl / "definitely_not_here")
    rep = cen.census({"A": {"download_dir": str(dl)},
                      "C": {"download_dir": gone},
                      "D": {}}, db, lf)

    reasons = {sid: why for sid, _, why in rep["unknown"]}
    assert set(reasons) == {"C", "D"}, rep["unknown"]
    assert "absent" in reasons["C"]
    assert "no download_dir" in reasons["D"]


def test_report_states_coverage_even_when_there_is_no_drift(lib):
    """A clean split over an empty denominator must not read as a clean
    library. This is the whole reason the census prints coverage."""
    db, lf, dl = lib
    rep = cen.census({"Z": {"download_dir": str(dl)}}, db, lf)
    text = cen.format_report(rep)

    assert len(rep["truncations"]) == 0 and len(rep["residue"]) == 0
    assert "rows examined : 0 of 5" in text, text
    assert "not in sites_config : 5" in text, text
    assert "complete -- every done row was examined" not in text, (
        "the report claimed completeness while examining nothing:\n" + text)
