#!/usr/bin/env python3
"""DECOMP-R1 — shim-over-rm generator + re-export completeness check.

`unzip -o` overlay cannot delete (hazard H-01). When a leaf module
`<pkg>/<target>.py` becomes a `<pkg>/<package>/` package, deploying by overlay
leaves the old `<target>.py` on stash, shadowing the package, so
`dependency_graph` re-counts the monolith and the in-sync gate FAILs. The robust
default (DECOMP-R1) is to keep `<target>.py` as an ADD-only re-export shim over
the package: no `rm`, no shadow, preflight `isfile(<target>.py)` stays green.

A shim is correct only if it re-exports EVERY name external importers pull from
the old module — including privates (H-04: `from pkg.<target> import _private`,
e.g. from an immovable release guard, must keep resolving). This tool derives
that importer-set from the source tree and emits / verifies the shim.

  python3 tools/decomp/make_shim.py --target templates --package site_templates --write
  python3 tools/decomp/make_shim.py --target templates --package site_templates --check

`--write` emits `<pkg>/<target>.py`; `--check` verifies an existing shim re-exports
the full live importer-set (exit 1 on any missing name). Never name a data package
`templates/` (H-08) — use e.g. `site_templates/`.
"""
from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def _iter_py(search_dirs):
    for d in search_dirs:
        d = Path(d)
        if not d.exists():
            continue
        for p in sorted(d.rglob("*.py")):
            if "__pycache__" in p.parts:
                continue
            yield p


def compute_required_reexports(target_stem, search_dirs, pkg_qualifier="bulk_downloader"):
    """Names that external importers pull from `<pkg_qualifier>.<target_stem>`.

    Detects both absolute (`from <pkg_qualifier>.<target> import a, b`) and
    intra-package relative (`from .<target> import a, b`) forms. Star imports are
    noted but cannot enumerate names; explicit names (incl. privates) are the
    set the shim must re-export. The target/package's own files are excluded.
    """
    required: set[str] = set()
    for p in _iter_py(search_dirs):
        # skip the target module itself and any file inside the new package dir
        if p.stem == target_stem or p.parent.name == target_stem:
            continue
        try:
            tree = ast.parse(p.read_text(encoding="utf-8", errors="replace"))
        except SyntaxError:
            continue
        for n in ast.walk(tree):
            if not isinstance(n, ast.ImportFrom):
                continue
            mod = n.module or ""
            is_abs = mod == f"{pkg_qualifier}.{target_stem}"
            is_rel = (n.level and mod == target_stem)
            if not (is_abs or is_rel):
                continue
            for a in n.names:
                if a.name != "*":
                    required.add(a.name)
    return required


def generate_shim(target_stem, package_name, required, pkg_qualifier="bulk_downloader"):
    """Emit ADD-only re-export shim text for `<target_stem>.py` over the package."""
    names = sorted(required)
    lines = [
        f'"""ADD-only re-export shim: {target_stem} -> {package_name}/ '
        f'(DECOMP-R1, H-01).',
        "",
        f"Keeps `{pkg_qualifier}.{target_stem}` importable after the module became",
        f"the `{package_name}/` package, so an `unzip -o` overlay never leaves a",
        "stale shadow on stash and every external importer (including private-name",
        "importers, H-04) keeps resolving. Generated by tools/decomp/make_shim.py;",
        "re-run with --write after the package's public surface changes.",
        '"""',
        f"from {pkg_qualifier}.{package_name} import *  # noqa: F401,F403",
    ]
    if names:
        lines.append(
            f"from {pkg_qualifier}.{package_name} import (  "
            f"# noqa: F401  explicit (incl. privates) -- H-04"
        )
        for nm in names:
            lines.append(f"    {nm},")
        lines.append(")")
    return "\n".join(lines) + "\n"


def _shim_reexports(shim_text):
    """Return (explicit_names:set, has_star:bool) re-exported by a shim."""
    explicit: set[str] = set()
    has_star = False
    try:
        tree = ast.parse(shim_text)
    except SyntaxError:
        return explicit, has_star
    for n in ast.walk(tree):
        if isinstance(n, ast.ImportFrom):
            for a in n.names:
                if a.name == "*":
                    has_star = True
                else:
                    explicit.add(a.name)
    return explicit, has_star


def check_shim_complete(shim_text, required):
    """Names in `required` the shim does NOT re-export.

    A `from pkg import *` covers public names only; a private (leading `_`) is
    covered solely by an explicit re-export (H-04). Returns the missing set.
    """
    explicit, has_star = _shim_reexports(shim_text)
    missing = set()
    for name in required:
        if name in explicit:
            continue
        if has_star and not name.startswith("_"):
            continue
        missing.add(name)
    return missing


def _default_search_dirs(root):
    return [root / "bulk_downloader", root / "tools"]


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--target", required=True, help="the module stem becoming a package")
    ap.add_argument("--package", required=True, help="the new package dir name")
    ap.add_argument("--pkg-qualifier", default="bulk_downloader")
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument("--write", action="store_true", help="emit <pkg>/<target>.py")
    g.add_argument("--check", action="store_true",
                   help="verify an existing shim re-exports the full importer-set")
    g.add_argument("--list", action="store_true", help="print the importer-set")
    args = ap.parse_args(argv)
    root = _repo_root()
    sdirs = _default_search_dirs(root)
    required = compute_required_reexports(args.target, sdirs, args.pkg_qualifier)
    shim_path = root / args.pkg_qualifier / f"{args.target}.py"

    if args.list:
        print(f"importer-set for {args.target} ({len(required)} names):")
        for nm in sorted(required):
            print(f"  {nm}")
        return 0

    if args.write:
        text = generate_shim(args.target, args.package, required, args.pkg_qualifier)
        shim_path.write_text(text, encoding="utf-8")
        print(f"wrote shim {shim_path.relative_to(root)} "
              f"re-exporting {len(required)} name(s)")
        return 0

    # --check
    if not shim_path.exists():
        print(f"FAIL: {shim_path.relative_to(root)} does not exist (no shim to check)")
        return 1
    missing = check_shim_complete(shim_path.read_text(encoding="utf-8"), required)
    if missing:
        print(f"FAIL: shim {shim_path.relative_to(root)} drops "
              f"{len(missing)} required name(s): {sorted(missing)}")
        return 1
    print(f"PASS: shim re-exports the full importer-set ({len(required)} names).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
