#!/bin/bash
# BulkDownloader — Claude Code cloud environment setup.
#
# Runs once at session start, BEFORE Claude Code launches.
#
# DESIGN NOTE (see CLAUDE.md section 0): the failure mode this script exists to
# avoid is a SILENTLY DEGRADED environment — one where an optional step failed,
# nothing said so, and a later "0 failures" result was really "0 of 0 examined".
# So every step records its outcome to a report file that Claude Code reads at
# the start of the session. Load-bearing steps hard-fail; optional steps degrade
# to a recorded WARN and are never silently skipped.

set -uo pipefail   # deliberately NOT -e: a failed optional step must be RECORDED,
                   # not abort provisioning and leave no explanation behind.

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"
REPORT="$REPO/.claude-env-report.md"
CORE_FAILED=0

: > "$REPORT"
{
  echo "# Environment provisioning report"
  echo
  echo "Generated by \`scripts/cloud-setup.sh\` at $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo "**Read this before trusting any test result.** A step marked WARN means a"
  echo "capability is absent, so suites depending on it will skip or fail for"
  echo "environmental reasons rather than code reasons."
  echo
  echo "| Step | Result | Detail |"
  echo "| --- | --- | --- |"
} >> "$REPORT"

row() { printf '| %s | %s | %s |\n' "$1" "$2" "$3" >> "$REPORT"; }

step() {                      # step <label> <core|optional> <command...>
  local label="$1" kind="$2"; shift 2
  local log; log="$(mktemp)"
  if "$@" > "$log" 2>&1; then
    row "$label" "OK" "$(tail -n 1 "$log" | tr '|' '/' | cut -c1-90)"
    echo "[ ok ] $label"
  else
    local rc=$?
    if [ "$kind" = core ]; then
      row "$label" "**FAILED**" "exit $rc — $(tail -n 3 "$log" | tr '\n' ' ' | tr '|' '/' | cut -c1-90)"
      echo "[FAIL] $label (exit $rc)"; sed 's/^/       /' "$log" | tail -n 15
      CORE_FAILED=1
    else
      row "$label" "WARN" "exit $rc — optional; dependent suites will not be able to run"
      echo "[warn] $label (exit $rc) — optional, recorded"
    fi
  fi
  rm -f "$log"
}

echo "=== BulkDownloader environment provisioning ==="
echo "repo: $REPO"

# ---------------------------------------------------------------- python core
step "python venv"        core  python3 -m venv venv
step "pip upgrade"        optional ./venv/bin/pip install -q --upgrade pip
step "runtime deps"       core  ./venv/bin/pip install -q -r requirements.txt

# pytest and pyflakes only. requirements-dev.txt additionally pulls
# pyinstaller + nuitka (~large) which exist for packaging work that is closed;
# a cloud dev box does not need them. Install them by hand if you resume MOD-7.
step "test deps"          core  ./venv/bin/pip install -q "pytest>=7.0,<9.0" pyflakes

# ------------------------------------------------------------------- frontend
# NOTE: this REQUIRES that NODE_ENV is not "production". Verified empirically:
# `NODE_ENV=production npm ci` omits devDependencies, which silently removes
# vite, typescript and vitest, and the build then fails with a confusing error.
# Do not set NODE_ENV=production in the environment variables panel.
if [ "${NODE_ENV:-}" = "production" ]; then
  row "NODE_ENV guard" "**FAILED**" "NODE_ENV=production omits devDependencies (vite/typescript). Unset it."
  echo "[FAIL] NODE_ENV=production would strip the frontend toolchain"
  CORE_FAILED=1
fi

if [ -f frontend/package-lock.json ]; then
  step "frontend deps"    optional bash -c 'cd frontend && npm ci --no-audit --no-fund'
else
  row "frontend deps" "WARN" "no package-lock.json — npm ci unavailable"
fi

# ------------------------------------------------------- playwright browsers
# ~150 MB and only needed by capture/recognizer suites. Opt in with
# BD_INSTALL_BROWSERS=1. Whichever way this goes it is RECORDED, so a skipped
# capture suite is never mistaken for a passing one.
if [ "${BD_INSTALL_BROWSERS:-0}" = "1" ]; then
  step "playwright chromium" optional ./venv/bin/python -m playwright install --with-deps chromium
else
  row "playwright chromium" "WARN" "skipped (BD_INSTALL_BROWSERS unset) — capture/recognizer suites CANNOT run"
  echo "[skip] playwright browsers — set BD_INSTALL_BROWSERS=1 to install"
fi

# ------------------------------------------------------------------ BD_HOME
# Runtime state must live OUTSIDE the tree. Writing it into the deployed code
# tree is a bug this project has already shipped and fixed once (v3.66.805).
mkdir -p "${BD_HOME:-/tmp/bd_home}" 2>/dev/null \
  && row "BD_HOME" "OK" "${BD_HOME:-/tmp/bd_home} (outside the repo, as required)" \
  || row "BD_HOME" "WARN" "could not create ${BD_HOME:-/tmp/bd_home}"

# ------------------------------------------------------------- verification
# Provisioning is not complete because the installers exited 0. Prove the
# package actually imports and reports the version the tree claims.
VER="$(./venv/bin/python -c 'import bulk_downloader;print(bulk_downloader.__version__)' 2>/dev/null)"
PINNED="$(grep -oE '__version__ *= *"[^"]+"' bulk_downloader/__init__.py | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')"
if [ -n "$VER" ] && [ "$VER" = "$PINNED" ]; then
  row "import check" "OK" "bulk_downloader $VER matches the tree"
  echo "[ ok ] import check — $VER"
else
  row "import check" "**FAILED**" "imported '${VER:-<none>}' but tree declares '${PINNED:-<none>}'"
  echo "[FAIL] import check — got '${VER:-<none>}', expected '${PINNED:-<none>}'"
  CORE_FAILED=1
fi

step "guard files" optional ./venv/bin/python - <<'PY'
import hashlib,sys
G={"bulk_downloader/extraction_core.py":"5b6248a5c9e664ab",
   "bulk_downloader/session_capture.py":"547d70c95cde9377",
   "bulk_downloader/dom_capture.py":"0559903d0b159162",
   "bulk_downloader/dom_recorder.py":"1657d0a0e39917ae",
   "bulk_downloader/capture_bodies.py":"6c7f5c9a87510cca",
   "tools/capture_session.py":"27be68b965689317",
   "tools/build_release.py":"f7c220d279fcfbee"}
bad=[f for f,w in G.items() if hashlib.sha256(open(f,'rb').read()).hexdigest()[:16]!=w]
print(f"{len(G)-len(bad)}/{len(G)} guard files match")
sys.exit(1 if bad else 0)
PY

# ------------------------------------------------------------------- summary
{
  echo
  if [ "$CORE_FAILED" -eq 1 ]; then
    echo "## VERDICT: INCOMPLETE"
    echo
    echo "A load-bearing step failed. Do not interpret test results from this"
    echo "environment as evidence about the code until it is fixed."
  else
    echo "## VERDICT: READY"
    echo
    echo "Core provisioning succeeded. Any WARN row above is a capability that is"
    echo "ABSENT, not one that passed — check this table before concluding that a"
    echo "suite is green."
  fi
  echo
  echo "Not attempted here, by design: the test suite (the operator runs it on the"
  echo "host), and the \`bd-*\` toolchain, of which 155 of 249 tools hardcode"
  echo "sandbox paths and cannot run against a clone."
} >> "$REPORT"

echo "=== provisioning $([ "$CORE_FAILED" -eq 1 ] && echo INCOMPLETE || echo READY) — report: $REPORT ==="
exit "$CORE_FAILED"
