#!/usr/bin/env python3
"""architecture_inventory.py — architecture write-up generator (A9).

Re-derives the architecture inventory FROM THE LIVE corrected dependency graph
(DEPENDENCY_GRAPH.json, the A3 tool) plus on-disk line counts, so the write-up
never goes stale-by-copy. Emits ARCHITECTURE_INVENTORY.md. Reports:

  * largest modules by LOC (refactor-attention candidates),
  * coupling hotspots (in-degree leaders from package.in — the modules whose
    change blast-radius is widest),
  * orphan candidates (package modules with NO inbound internal edge) — these
    are TRIAGE candidates, NEVER blind-delete targets (entry points such as
    app.py / runner.py legitimately have no importers),
  * blueprint route-count summary (from the graph's blueprint section).

STRICTLY READ-ONLY except writing the one report file. stdlib-only; it reads the
graph JSON and walks the tree for LOC — it imports no package module and runs
nothing. If the graph is stale, run `python3 tools/dependency_graph.py` first.

CLI:  python3 tools/architecture_inventory.py [--root .] [--top N] [--json] [--out PATH]
"""
from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

_GRAPH = "DEPENDENCY_GRAPH.json"
_DEFAULT_OUT = "ARCHITECTURE_INVENTORY.md"


def _loc(path: Path) -> int:
    try:
        with path.open("rb") as f:
            return sum(1 for _ in f)
    except OSError:
        return 0


def _module_locs(root: Path):
    out = {}
    for sub in ("bulk_downloader", "tools"):
        base = root / sub
        if not base.is_dir():
            continue
        for p in base.rglob("*.py"):
            if "__pycache__" in p.parts:
                continue
            out[str(p.relative_to(root))] = _loc(p)
    return out


def build(root="."):
    root = Path(root)
    gpath = root / _GRAPH
    if not gpath.is_file():
        raise FileNotFoundError(f"{_GRAPH} not found — run tools/dependency_graph.py first")
    g = json.loads(gpath.read_text("utf-8"))
    pkg = g.get("package", {})
    indeg = pkg.get("in", {})    # module -> [importers]
    outdeg = pkg.get("out", {})  # module -> [imports]
    locs = _module_locs(root)

    largest = sorted(locs.items(), key=lambda kv: kv[1], reverse=True)
    hotspots = sorted(((m, len(v)) for m, v in indeg.items()),
                      key=lambda kv: kv[1], reverse=True)

    # orphan candidates: a bulk_downloader/*.py on disk that nothing imports
    # (no inbound internal edge). Entry points are expected here — triage only.
    pkg_modules = [m for m in locs if m.startswith("bulk_downloader/")
                   and not m.endswith("__init__.py")]
    orphans = sorted(m for m in pkg_modules if not indeg.get(m))

    blueprints = {name: b.get("route_count", len(b.get("routes", [])))
                  for name, b in (g.get("blueprint", {}) or {}).items()}

    return {
        "graph_version": g.get("graph_version"),
        "edge_count": pkg.get("edge_count"),
        "module_count": len(locs),
        "largest": largest,
        "hotspots": hotspots,
        "orphan_candidates": orphans,
        "blueprints": blueprints,
        "total_loc": sum(locs.values()),
    }


def render_md(d, top=15):
    L = ["# Architecture inventory",
         "",
         "*Generated by `tools/architecture_inventory.py` from the live "
         "`DEPENDENCY_GRAPH.json` (A3) + on-disk line counts. Regenerate after "
         "structural changes; do not hand-edit. Read-only snapshot — numbers "
         "reflect the tree at generation time.*",
         "",
         f"- dependency-graph version: `{d['graph_version']}`  ·  internal edges: "
         f"**{d['edge_count']}**",
         f"- python modules (package + tools): **{d['module_count']}**  ·  total LOC: "
         f"**{d['total_loc']:,}**",
         "",
         f"## Largest modules (top {top}) — refactor-attention candidates",
         "",
         "| module | LOC |",
         "|---|---:|"]
    for m, n in d["largest"][:top]:
        L.append(f"| `{m}` | {n:,} |")
    L += ["",
          f"## Coupling hotspots (top {top} by in-degree) — widest change blast-radius",
          "",
          "*In-degree = how many internal modules import this one. A change here "
          "ripples to every importer; these are the highest-risk edits.*",
          "",
          "| module | in-degree |",
          "|---|---:|"]
    for m, n in d["hotspots"][:top]:
        L.append(f"| `{m}` | {n} |")
    L += ["",
          "## Orphan candidates (no inbound internal edge)",
          "",
          "**TRIAGE ONLY — never blind-delete.** Entry points (`app.py`, `runner.py`), "
          "CLI mains, blueprint modules wired by string/registration, and "
          "dynamically-imported modules legitimately show zero static importers. "
          "Each needs individual confirmation before any removal.",
          ""]
    if d["orphan_candidates"]:
        for m in d["orphan_candidates"]:
            L.append(f"- `{m}`")
    else:
        L.append("- (none)")
    L += ["",
          "## Blueprints (route counts)",
          "",
          "| blueprint | routes |",
          "|---|---:|"]
    for name in sorted(d["blueprints"]):
        L.append(f"| {name} | {d['blueprints'][name]} |")
    L.append("")
    return "\n".join(L)


def main(argv=None):
    ap = argparse.ArgumentParser(description="Architecture inventory generator (A9).")
    ap.add_argument("--root", default=".")
    ap.add_argument("--top", type=int, default=15)
    ap.add_argument("--out", default=_DEFAULT_OUT)
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args(argv)
    d = build(args.root)
    if args.json:
        print(json.dumps(d, indent=2))
        return 0
    md = render_md(d, top=args.top)
    out = Path(args.root) / args.out
    out.write_text(md, "utf-8")
    print(f"WROTE: {out} ({md.count(chr(10)) + 1} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
