#!/usr/bin/env python3
"""Build INV_TAGS.md as a deterministic current-source locality view."""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "INV_TAGS.md"
TAG = re.compile(r"#\s*(INV-\d+)")


def tracked_python() -> list[str]:
    result = subprocess.run(
        ["git", "-C", str(ROOT), "ls-files", "-z", "bulk_downloader/*.py"],
        check=True, capture_output=True)
    return sorted(p for p in result.stdout.decode().split("\0") if p)


def render() -> str:
    found: dict[str, list[tuple[str, int, str]]] = defaultdict(list)
    for rel in tracked_python():
        for lineno, line in enumerate((ROOT / rel).read_text(
                encoding="utf-8", errors="replace").splitlines(), 1):
            for inv_id in TAG.findall(line):
                found[inv_id].append((rel, lineno, line.strip()))
    if not found:
        raise RuntimeError("UNKNOWN: zero current-source INV-NNN tags found")
    lines = [
        "# INV_TAGS.md — GENERATED CURRENT-SOURCE VIEW",
        "",
        "Generated by `python tools/build_inv_tags.py`. Do not edit by hand.",
        "Root `INVARIANTS.json`, current source, and point-of-use tests are",
        "authoritative; this file is only a deterministic locality view.",
        "",
    ]
    for inv_id in sorted(found, key=lambda value: int(value.split("-")[1])):
        lines += [f"## {inv_id} — live source tags", ""]
        for rel, lineno, text in found[inv_id]:
            lines.append(f"- `{rel}:{lineno}` — `{text.replace('`', '')}`")
        lines.append("")
    count = sum(map(len, found.values()))
    lines += ["## Inventory summary", "",
              f"- **{count} `# INV-` tag occurrences** across "
              f"{len({rel for hits in found.values() for rel, _, _ in hits})} tracked Python files.",
              f"- **{len(found)} invariant IDs** observed in current source.", ""]
    return "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args(argv)
    expected = render()
    if args.check:
        actual = OUT.read_text(encoding="utf-8") if OUT.is_file() else ""
        if actual != expected:
            print("STALE: run python tools/build_inv_tags.py", file=sys.stderr)
            return 1
        print("PASS: INV_TAGS.md matches current tracked source")
        return 0
    OUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
