#!/usr/bin/env python3
"""
document_schemas.py — generate schema documentation from source (#13 / P9).

Read-only. Two schemas, one markdown doc:

  1. SQLite schema — extracted from the CREATE TABLE / CREATE INDEX statements in
     bulk_downloader/db.py (source is the single truth; this never opens a live DB).
  2. Template schema — introspected from a reviewed gold template plus the field
     contract that tools/template_inventory.py scores against, so the doc and the
     scorer can't drift.

CLI:
    python3 tools/document_schemas.py [--root .] [--out OUT.md]   # stdout if no --out
"""
import argparse
import glob
import json
import os
import re
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE))
sys.path.insert(0, str(_HERE.parent))

_TABLE_RE = re.compile(
    r"CREATE TABLE IF NOT EXISTS\s+(\w+)\s*\((.*?)\)\"\"\"", re.S)
_INDEX_RE = re.compile(
    r"CREATE INDEX IF NOT EXISTS\s+(\w+)\s+ON\s+([^\"]+?)\"")


def _db_schema(root):
    p = os.path.join(root, "bulk_downloader", "db.py")
    try:
        src = open(p).read()
    except OSError:
        return [], []
    tables = []
    for name, body in _TABLE_RE.findall(src):
        cols = [ln.strip().rstrip(",")
                for ln in body.splitlines() if ln.strip()]
        tables.append((name, cols))
    indexes = [(n, tgt.strip()) for n, tgt in _INDEX_RE.findall(src)]
    return tables, indexes


def _template_contract(root):
    try:
        import template_inventory as TI  # type: ignore
        weights = TI._WEIGHTS
    except Exception:  # noqa: BLE001
        weights = {}
    gold = None
    files = sorted(glob.glob(os.path.join(root, "templates", "reviewed", "*.json")))
    if files:
        try:
            gold = json.load(open(files[0]))
        except (OSError, ValueError):
            gold = None
    return weights, gold, (os.path.basename(files[0]) if files else None)


def render(root="."):
    tables, indexes = _db_schema(root)
    weights, gold, gold_name = _template_contract(root)
    L = ["# Generated schema reference", "",
         "Auto-generated by `tools/document_schemas.py` from source — do not hand-edit.",
         "", "## 1. SQLite schema (from `bulk_downloader/db.py`)", ""]
    if not tables:
        L.append("_(no CREATE TABLE statements found)_")
    for name, cols in tables:
        L += [f"### `{name}`", ""]
        for c in cols:
            L.append(f"- `{c}`")
        L.append("")
    if indexes:
        L += ["### Indexes", ""]
        for n, tgt in indexes:
            L.append(f"- `{n}` on `{tgt}`")
        L.append("")
    L += ["## 2. Template schema", ""]
    if gold:
        L += [f"Introspected from `templates/reviewed/{gold_name}`.", "",
              f"- schema marker: `{gold.get('schema')}`",
              f"- top-level keys: {', '.join('`%s`' % k for k in sorted(gold.keys()))}",
              f"- selector groups: {', '.join('`%s`' % k for k in sorted((gold.get('selectors') or {}).keys()))}",
              f"- api keys: {', '.join('`%s`' % k for k in sorted((gold.get('api') or {}).keys()))}",
              ""]
    else:
        L.append("_(no reviewed template found to introspect)_")
    if weights:
        L += ["### Completeness contract (what `template_inventory` scores)", "",
              "Each present field adds its weight to a 0-100 completeness score:", ""]
        for k, w in weights.items():
            L.append(f"- `{k}`: {w}")
        L += ["",
              "Promotion gate (mirrors `promote_template.py`): "
              "`(download.trigger | download.row_selectors | download.button)` "
              "+ non-empty `resolutions` + no blocked terms.", ""]
    L += ["### Status values", "",
          "- `enabled` — reviewed/active; the registry loads only these.",
          "- `draft_requires_review` / `draft_review_required` — draft/not-ready "
          "(both spellings are present in the codebase; tools accept either).",
          "- `review_ready` — a normalized candidate that passes the gate.", ""]
    return "\n".join(L) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description="Generate schema docs (read-only).")
    ap.add_argument("--root", default=".")
    ap.add_argument("--out", metavar="OUT")
    args = ap.parse_args(argv)
    text = render(args.root)
    if args.out:
        with open(args.out, "w") as fh:
            fh.write(text)
        print(f"wrote {args.out}")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
