#!/usr/bin/env python3
"""gen_reference_docs.py — generate reference docs, derived where possible (J).
Writes to --outdir (default docs/):
  CONFIG_REFERENCE.md   (DB schema + config validators)
  TEMPLATE_REFERENCE.md (template contract, from document_schemas)
  CAPTURE_REFERENCE.md  (capture metrics)
  REPORTING_REFERENCE.md(report generators + their outputs)
  RELEASE_REFERENCE.md  (release checklist + changelog stats)
Read-only except the generated files. CLI: --root, --outdir
"""
import argparse, os, sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent))
import document_schemas as DS  # type: ignore
import changelog_analyzer as CL  # type: ignore

REPORT_TOOLS = [
    ("template_health_report.py", "reports/template_health.{json,md}"),
    ("capture_quality_report.py", "reports/capture_analytics.md"),
    ("release_diff_summary.py", "reports/release_history.md"),
    ("dependency_inventory.py", "reports/codebase_inventory.md"),
    ("test_runtime_report.py", "reports/test_health.md"),
    ("technical_debt_report.py", "reports/technical_debt.md"),
    ("compat_shim_audit.py", "reports/compat_shim_audit.md"),
    ("offline_pack_report.py", "reports/offline_pack_report.md"),
    ("environment_report.py", "reports/environment.md"),
    ("kb_audit.py", "reports/kb_health.md"),
]


def _config_ref(root):
    schema = DS.render(root)
    db = schema.split("## 2. Template schema")[0]
    return ("# Config reference\n\n"
            "Generated by `tools/gen_reference_docs.py`. Validators: "
            "`validate_sites_config.py`, `validate_global_config.py`, "
            "`validate_templates.py`.\n\n" + db)


def _template_ref(root):
    schema = DS.render(root)
    tmpl = "## 2. Template schema" + schema.split("## 2. Template schema")[1]
    return "# Template reference\n\nGenerated by `tools/gen_reference_docs.py`.\n\n" + tmpl


def _capture_ref():
    return ("# Capture reference\n\n"
            "Capture quality metrics (`tools/capture_quality_report.py`):\n\n"
            "- WACZ count, capture-JSON count\n- DOM event count, snapshot count\n"
            "- rrweb coverage, snapdom coverage\n"
            "- template generation success rate (gate-ready candidates / yield)\n\n"
            "Artifacts live on the operator host; in a clean tree only yield-based "
            "metrics are populated.\n")


def _reporting_ref():
    L = ["# Reporting reference", "",
         "All report generators are read-only and write under `reports/`.", "",
         "| tool | output |", "|------|--------|"]
    for t, out in REPORT_TOOLS:
        L.append(f"| `tools/{t}` | `{out}` |")
    L += ["", "Dashboard data layer: `/api/data/{template_health,capture_analytics,"
          "queue_analytics,release_analytics,kb_analytics}` "
          "(`bulk_downloader/app_data_layer.py`).",
          "Report Center page: `/cockpit/reports` (`app_report_center.py`)."]
    return "\n".join(L) + "\n"


def _release_ref(root):
    cl = CL.parse(root)
    return ("# Release reference\n\n"
            "Release gate: `tools/verify_release.py` (version + docs + templates + "
            "zip manifest + tests). See `docs/VERIFY_RELEASE.md`.\n\n"
            f"Changelog: **{cl['count']}** releases, **{cl['totals']['features']}** "
            f"feature bullets, **{cl['totals']['fixes']}** fix bullets.\n\n"
            "Checklist: bump `bulk_downloader/__init__.py` __version__; prepend a "
            "matching `## vX.Y.Z` CHANGELOG entry; regen ENDPOINT_CATALOG / "
            "FUNCTION_INDEX if routes/functions changed; build; verify from the "
            "extracted zip.\n")


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default="."); ap.add_argument("--outdir", default="docs")
    a = ap.parse_args(argv)
    os.makedirs(a.outdir, exist_ok=True)
    docs = {"CONFIG_REFERENCE.md": _config_ref(a.root),
            "TEMPLATE_REFERENCE.md": _template_ref(a.root),
            "CAPTURE_REFERENCE.md": _capture_ref(),
            "REPORTING_REFERENCE.md": _reporting_ref(),
            "RELEASE_REFERENCE.md": _release_ref(a.root)}
    for name, text in docs.items():
        open(os.path.join(a.outdir, name), "w").write(text)
    print("wrote", ", ".join(docs))
    return 0


if __name__ == "__main__":
    sys.exit(main())
