#!/usr/bin/env python3
"""Generate frontend/src/lib/secretKeys.generated.ts from the server SoT.

REDACT-SOT Cut 3 (D3): the frontend previously hand-maintained two secret-key
mirrors that drifted from the server -- Vpn.tsx SECRET_KEY_HINTS (config domain)
and copySiteConfig.ts SECRET_KEY (URL/query domain). Both now consume a single
generated constants file emitted from the authoritative server sources, so a
server-side keyword change can never silently desync the GUI.

Two domains are emitted (matching the two server SoTs):

  * CONFIG domain (site_editor):  SECRET_FIELDS (exact) + _CONFIG_SECRET_FLOOR
    (substring) + vpn._SECRET_KEY_HINTS (the VPN conservative extra; canonical @773).
    Consumed by Vpn.tsx to decide which config rows render write-only.

  * URL/QUERY domain (capture_redact.SENSITIVE_QS_KEY): the substring alternation
    terms + the anchored-exact tail. Consumed by copySiteConfig.ts for clipboard
    masking.

The generated file carries a header sentinel and a source-hash so a sync test
(tests/test_frontend_secret_keys_in_sync.py) fails RED if the server changes and
this generator was not re-run. Run: python tools/gen_frontend_secret_keys.py
[--check].

Deliberately extracts URL terms from the compiled pattern rather than refactoring
the redaction-critical SENSITIVE_QS_KEY regex (whose anchoring semantics are
subtle); the config domain emits from the existing clean list constants.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parent.parent
_OUT = _REPO / "frontend" / "src" / "lib" / "secretKeys.generated.ts"

_HEADER = "// AUTO-GENERATED by tools/gen_frontend_secret_keys.py -- DO NOT EDIT.\n"


def _server_sources() -> dict:
    """Pull the authoritative keyword sets from the server modules."""
    sys.path.insert(0, str(_REPO))
    from bulk_downloader.site_editor import _CONFIG_SECRET_FLOOR, SECRET_FIELDS
    # v3.66.773: the canonical VPN secret-key hints moved to vpn (vpn_config now
    # derives from it), so read the SoT directly from vpn.
    from bulk_downloader.vpn import _SECRET_KEY_HINTS
    from bulk_downloader.capture_redact import SENSITIVE_QS_KEY

    # URL/query domain: split the compiled pattern into the substring alternation
    # group and the anchored-exact tail ``^(?:a|b|c)$``.
    pat = SENSITIVE_QS_KEY.pattern
    substr_terms: list[str] = []
    anchored_terms: list[str] = []
    expected_flags = re.IGNORECASE | re.UNICODE
    if SENSITIVE_QS_KEY.flags != expected_flags:
        raise RuntimeError(
            "SENSITIVE_QS_KEY flags changed; frontend lowercasing assumes "
            "exact IGNORECASE|UNICODE semantics"
        )
    shape = re.fullmatch(r"\(([^()]*)\)\|\^\(\?:([^()]*)\)\$", pat)
    if not shape:
        raise RuntimeError(
            "SENSITIVE_QS_KEY no longer has the reviewed substring|anchored-exact "
            "shape; refuse partial frontend extraction"
        )
    substr_terms = [t for t in shape.group(1).split("|") if t]
    anchored_terms = [t for t in shape.group(2).split("|") if t]
    if (not substr_terms or not anchored_terms
            or any(re.search(r"[^A-Za-z0-9_-]", term)
                   for term in substr_terms + anchored_terms)):
        raise RuntimeError("SENSITIVE_QS_KEY terms are empty or not literal-safe")

    return {
        "config_floor": sorted(set(_CONFIG_SECRET_FLOOR)),
        "config_fields": sorted(set(SECRET_FIELDS)),
        "vpn_hints": sorted(set(_SECRET_KEY_HINTS)),
        "url_substrings": substr_terms,
        "url_anchored": anchored_terms,
        # Clipboard-copy domain (copySiteConfig.ts): the URL substrings PLUS bare
        # "cookie" (server SENSITIVE_HEADER covers Cookie; SENSITIVE_QS_KEY has
        # only "cookies") PLUS the always-secret token-class members of the
        # anchored tail (otp/nonce), but deliberately NOT the ambiguous bare keys
        # code/k/tk/ak/sk/state (F-FE09-01: often benign config fields). Composed
        # here so it stays server-sourced and drift-guarded.
        "clipboard_terms": sorted(
            set(substr_terms) | {"cookie"}
            | ({"otp", "nonce"} & set(anchored_terms))
        ),
    }


def _render(src: dict) -> str:
    payload = json.dumps(src, sort_keys=True)
    digest = hashlib.sha256(payload.encode()).hexdigest()[:16]

    def arr(name: str, items: list[str]) -> str:
        body = ", ".join(json.dumps(x) for x in items)
        return f"export const {name}: readonly string[] = [{body}];\n"

    lines = [
        _HEADER,
        f"// source-sha: {digest}\n",
        "//\n",
        "// Mirrors the server redaction SoT. Regenerate with:\n",
        "//   python tools/gen_frontend_secret_keys.py\n",
        "\n",
        "// --- config-field domain (site_editor + vpn_config) ---\n",
        arr("CONFIG_SECRET_FIELDS", src["config_fields"]),
        arr("CONFIG_SECRET_FLOOR", src["config_floor"]),
        arr("VPN_SECRET_HINTS", src["vpn_hints"]),
        "\n",
        "// --- URL/query domain (capture_redact.SENSITIVE_QS_KEY) ---\n",
        arr("URL_SECRET_SUBSTRINGS", src["url_substrings"]),
        arr("URL_SECRET_ANCHORED", src["url_anchored"]),
        "\n",
        "// --- clipboard-copy domain (copySiteConfig.ts) ---\n",
        arr("CLIPBOARD_SECRET_TERMS", src["clipboard_terms"]),
        "\n",
        "export const SECRET_KEYS_SOURCE_SHA = "
        f"{json.dumps(digest)};\n",
        "\n",
        "// Config-domain predicate: mirrors site_editor.is_secret_config_key\n",
        "// (fail-open floor UNION exact SECRET_FIELDS).\n",
        "export function isSecretConfigKey(k: string): boolean {\n",
        "  if (CONFIG_SECRET_FIELDS.includes(k)) return true;\n",
        "  const kl = k.toLowerCase();\n",
        "  return CONFIG_SECRET_FLOOR.some((m) => kl.includes(m));\n",
        "}\n",
        "\n",
        "// VPN config predicate: mirrors vpn_config._vpn_key_is_secret\n",
        "// (config-domain UNION the conservative VPN hints).\n",
        "export function isVpnSecretKey(k: string): boolean {\n",
        "  const kl = k.toLowerCase();\n",
        "  return isSecretConfigKey(k) || VPN_SECRET_HINTS.some((h) => kl.includes(h));\n",
        "}\n",
        "\n",
        "// URL/query predicate: mirrors capture_redact.SENSITIVE_QS_KEY\n",
        "// (substring alternation OR anchored-exact tail).\n",
        "export function isUrlSecretKey(k: string): boolean {\n",
        "  const kl = k.toLowerCase();\n",
        "  if (URL_SECRET_SUBSTRINGS.some((s) => kl.includes(s))) return true;\n",
        "  return URL_SECRET_ANCHORED.includes(kl);\n",
        "}\n",
        "\n",
        "// Clipboard-copy predicate: URL substrings + bare cookie + the\n",
        "// always-secret token-class (otp/nonce), excluding ambiguous code/state.\n",
        "export function isClipboardSecretKey(k: string): boolean {\n",
        "  const kl = k.toLowerCase();\n",
        "  return CLIPBOARD_SECRET_TERMS.some((s) => kl.includes(s));\n",
        "}\n",
    ]
    return "".join(lines)


def generate() -> str:
    return _render(_server_sources())


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if the committed file is stale")
    args = ap.parse_args()

    content = generate()
    if args.check:
        if not _OUT.exists() or _OUT.read_text() != content:
            print("STALE: secretKeys.generated.ts is out of sync with the server "
                  "SoT; run python tools/gen_frontend_secret_keys.py", file=sys.stderr)
            return 1
        print("OK: secretKeys.generated.ts in sync")
        return 0
    _OUT.write_text(content)
    print(f"wrote {_OUT.relative_to(_REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
