// AUTO-GENERATED by tools/gen_frontend_secret_keys.py -- DO NOT EDIT.
// source-sha: 6aa363702e74a7f8
//
// Mirrors the server redaction SoT. Regenerate with:
//   python tools/gen_frontend_secret_keys.py

// --- config-field domain (site_editor + vpn_config) ---
export const CONFIG_SECRET_FIELDS: readonly string[] = ["ai_api_key", "auth_token", "captcha_api_key", "ha_token", "jellyfin_api_key", "password", "plex_token", "qb_password", "stash_api_key", "tpdb_api_key"];
export const CONFIG_SECRET_FLOOR: readonly string[] = ["api_key", "apikey", "cookies", "credential", "passphrase", "passwd", "password", "preshared", "private_key", "privatekey", "secret", "token", "vault"];
export const VPN_SECRET_HINTS: readonly string[] = ["account_number", "auth", "credential", "key", "passwd", "password", "private", "secret", "token"];

// --- URL/query domain (capture_redact.SENSITIVE_QS_KEY) ---
export const URL_SECRET_SUBSTRINGS: readonly string[] = ["token", "key", "sig", "signature", "secret", "auth", "session", "sid", "hash", "expires", "policy", "credential", "x-amz-", "apikey", "password", "pwd", "jwt", "hdnea", "hdnts", "__gda__", "challenge", "cf_chl", "captcha", "csrf", "xsrf", "bearer"];
export const URL_SECRET_ANCHORED: readonly string[] = ["code", "k", "nonce", "otp", "tk", "ak", "sk", "state"];

// --- clipboard-copy domain (copySiteConfig.ts) ---
export const CLIPBOARD_SECRET_TERMS: readonly string[] = ["__gda__", "apikey", "auth", "bearer", "captcha", "cf_chl", "challenge", "cookie", "credential", "csrf", "expires", "hash", "hdnea", "hdnts", "jwt", "key", "nonce", "otp", "password", "policy", "pwd", "secret", "session", "sid", "sig", "signature", "token", "x-amz-", "xsrf"];

export const SECRET_KEYS_SOURCE_SHA = "6aa363702e74a7f8";

// Config-domain predicate: mirrors site_editor.is_secret_config_key
// (fail-open floor UNION exact SECRET_FIELDS).
export function isSecretConfigKey(k: string): boolean {
  if (CONFIG_SECRET_FIELDS.includes(k)) return true;
  const kl = k.toLowerCase();
  return CONFIG_SECRET_FLOOR.some((m) => kl.includes(m));
}

// VPN config predicate: mirrors vpn_config._vpn_key_is_secret
// (config-domain UNION the conservative VPN hints).
export function isVpnSecretKey(k: string): boolean {
  const kl = k.toLowerCase();
  return isSecretConfigKey(k) || VPN_SECRET_HINTS.some((h) => kl.includes(h));
}

// URL/query predicate: mirrors capture_redact.SENSITIVE_QS_KEY
// (substring alternation OR anchored-exact tail).
export function isUrlSecretKey(k: string): boolean {
  const kl = k.toLowerCase();
  if (URL_SECRET_SUBSTRINGS.some((s) => kl.includes(s))) return true;
  return URL_SECRET_ANCHORED.includes(kl);
}

// Clipboard-copy predicate: URL substrings + bare cookie + the
// always-secret token-class (otp/nonce), excluding ambiguous code/state.
export function isClipboardSecretKey(k: string): boolean {
  const kl = k.toLowerCase();
  return CLIPBOARD_SECRET_TERMS.some((s) => kl.includes(s));
}
